/* 개인연금 V2.0 RC6 - 저장·ZIP 백업·복원 */
'use strict';
(()=>{
const enc=new TextEncoder(),dec=new TextDecoder();
const DB_NAME='investment-os-pension-v2',STORE='records',CURRENT='current',SAFETY='pre-restore-safety';
const PROJECT_ASSETS=['index.html','base.css','app.css','state.js','engine.js','ledger.js','coach.js','views.js','forms.js','ocr.js','backup.js','integrity.js','app.js','manifest.webmanifest','sw.js','icon.svg'];
const DATA_REQUIRED=['full-backup.json','accounts.csv','transactions.csv','contributions.csv','dividends.csv','snapshots.csv','archived-holdings.csv','settings.csv','backup-schema.txt','recovery-guide.md','manifest.json'];
let dbPromise=null,restoreCandidate=null;
function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return dbPromise}
async function dbPut(key,value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function dbGet(key){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function persist(copy){try{state.meta.storage.localStatus='저장 중';await dbPut(CURRENT,copy);state.meta.storage.localStatus='정상';state.meta.storage.lastLocalSave=new Date().toLocaleString('ko-KR');refreshDataCenter()}catch(e){state.meta.storage.localStatus='실패';state.meta.storage.localError=String(e?.message||e);refreshDataCenter()}}
async function hydrate(){try{const saved=await dbGet(CURRENT);if(saved){const currentTime=Date.parse(state.meta?.updatedAt||0)||0,savedTime=Date.parse(saved.meta?.updatedAt||0)||0;if(savedTime>currentTime||(Number(saved.meta?.revision)||0)>(Number(state.meta?.revision)||0)){state=ensureSchema6(clone(saved));localStorage.setItem(STORAGE_KEY,JSON.stringify(state));return true}}}catch(e){console.warn('IndexedDB 불러오기 실패',e)}return false}
const csvCell=v=>`"${String(v??'').replace(/"/g,'""')}"`;
const csv=(headers,rows)=>'\uFEFF'+[headers.map(csvCell).join(','),...rows.map(row=>headers.map(h=>csvCell(row[h])).join(','))].join('\n');
function counts(s){return {accounts:Object.keys(s.accounts||{}).length,holdings:Object.values(s.accounts||{}).reduce((n,a)=>n+(a.holdings||[]).length,0),transactions:(s.ledger||[]).length,contributions:(s.ledger||[]).filter(r=>r.type==='contribution').length,dividends:(s.ledger||[]).filter(r=>r.type==='dividend').length,snapshots:(s.snapshots||[]).length,years:Object.keys(s.years||{}).length,totalAssets:Object.values(s.accounts||{}).reduce((sum,a)=>sum+(Number(a.cash)||0)+(a.holdings||[]).reduce((x,h)=>x+Number(h.value||0),0),0)}}
function coreBackup(s){const copy=clone(s);delete copy.ui;copy.meta=copy.meta||{};copy.meta.appVersion=APP_VERSION;copy.meta.backupCreatedAt=isoNow();return copy}
function backupFiles(s){
  const data=coreBackup(s),accountRows=[],txRows=(data.ledger||[]).map(r=>({...r,extensions:JSON.stringify(r.extensions||{})}));
  for(const [key,a] of Object.entries(data.accounts||{}))for(const h of a.holdings||[])accountRows.push({accountKey:key,accountId:a.id,accountName:a.name,principal:a.principal,cash:a.cash,holdingId:h.id,name:h.name,class:h.class,qty:h.qty,value:h.value,cost:h.cost,dividend:h.dividend,realized:h.realized,risk:h.risk,status:h.status});
  const contributionRows=txRows.filter(r=>r.type==='contribution'),dividendRows=txRows.filter(r=>['dividend','dividend-adjustment','dividend-account-allocation'].includes(r.type)),snapshotRows=(data.snapshots||[]).map(s=>({...s,holdings:JSON.stringify(s.holdings||s.accounts||{})})),archiveRows=(data.archives?.holdings||[]).map(h=>({...h,extensions:JSON.stringify(h.extensions||{})}));
  return {
    'full-backup.json':JSON.stringify({backupFormatVersion:'2.0',appId:APP_ID,appVersion:APP_VERSION,schemaVersion:SCHEMA_VERSION,createdAt:isoNow(),data},null,2),
    'accounts.csv':csv(['accountKey','accountId','accountName','principal','cash','holdingId','name','class','qty','value','cost','dividend','realized','risk','status'],accountRows),
    'transactions.csv':csv(['id','type','date','monthKey','year','accountKey','accountId','assetId','assetName','amount','quantity','realized','principalDelta','cashDelta','note','source','status'],txRows),
    'contributions.csv':csv(['id','date','monthKey','year','accountKey','amount','note','status'],contributionRows),
    'dividends.csv':csv(['id','date','monthKey','year','accountKey','assetName','amount','status'],dividendRows),
    'snapshots.csv':csv(['id','createdAt','effectiveDate','accountKey','total','cash','reason','holdings'],snapshotRows),
    'archived-holdings.csv':csv(['id','accountId','name','class','qty','value','cost','archivedAt','archiveReason','status'],archiveRows),
    'settings.csv':csv(['key','value'],[['profile',JSON.stringify(data.profile)],['settings',JSON.stringify(data.settings)],['lastUpdated',data.lastUpdated],['dataId',data.dataId]].map(([key,value])=>({key,value}))),
    'backup-schema.txt':`개인연금 V2.0 표준 백업\nappId: ${APP_ID}\nappVersion: ${APP_VERSION}\nschemaVersion: ${SCHEMA_VERSION}\n\nfull-backup.json이 완전 복원 원본입니다. CSV는 열람·이전용입니다. 사진 원본은 포함하지 않습니다. 앱 버전과 데이터 구조 버전은 별도로 관리합니다.`,
    'recovery-guide.md':'# 개인연금 복구 안내\n\n1. 새 개인연금 앱을 엽니다.\n2. 설정 → 백업·복원 → 백업 파일 불러오기를 선택합니다.\n3. 이 ZIP을 선택하고 미리보기의 계좌·기록·총자산을 확인합니다.\n4. 앱은 현재 데이터를 안전백업한 후에만 교체합니다.\n'
  };
}
let crcTable=null;function crc32(bytes){if(!crcTable){crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0})}let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
const u16=n=>new Uint8Array([n&255,(n>>>8)&255]),u32=n=>new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);
function concat(parts){const len=parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(len);let off=0;for(const p of parts){out.set(p,off);off+=p.length}return out}
function zipCreate(files){const local=[],central=[];let offset=0;for(const [name,content] of Object.entries(files)){const nameBytes=enc.encode(name),data=content instanceof Uint8Array?content:enc.encode(String(content)),crc=crc32(data),localHeader=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(nameBytes.length),u16(0),nameBytes]);local.push(localHeader,data);central.push(concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(nameBytes.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),nameBytes]));offset+=localHeader.length+data.length}const centralBytes=concat(central),end=concat([u32(0x06054b50),u16(0),u16(0),u16(central.length),u16(central.length),u32(centralBytes.length),u32(offset),u16(0)]);return concat([...local,centralBytes,end])}
const r16=(b,o)=>b[o]|b[o+1]<<8,r32=(b,o)=>(b[o]|b[o+1]<<8|b[o+2]<<16|b[o+3]<<24)>>>0;
function zipRead(bytes){const out={};let pos=0;while(pos+30<=bytes.length&&r32(bytes,pos)===0x04034b50){const method=r16(bytes,pos+8),crc=r32(bytes,pos+14),comp=r32(bytes,pos+18),size=r32(bytes,pos+22),nameLen=r16(bytes,pos+26),extraLen=r16(bytes,pos+28),name=dec.decode(bytes.slice(pos+30,pos+30+nameLen)),start=pos+30+nameLen+extraLen;if(method!==0)throw new Error('지원하지 않는 ZIP 압축 방식입니다.');const data=bytes.slice(start,start+comp);if(data.length!==size||crc32(data)!==crc)throw new Error(`${name} 파일이 손상되었습니다.`);out[name]=data;pos=start+comp}if(!Object.keys(out).length)throw new Error('ZIP 파일을 열 수 없습니다.');return out}
async function sha256(data){const bytes=data instanceof Uint8Array?data:enc.encode(String(data));if(crypto.subtle){const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}return crc32(bytes).toString(16).padStart(8,'0')}
function validateData(data){const errors=[];try{ensureSchema6(clone(data))}catch(e){errors.push(e.message)}if(data.appId!==APP_ID)errors.push('앱 식별자가 다릅니다.');if(Number(data.schemaVersion)>SCHEMA_VERSION)errors.push('더 새로운 데이터 구조입니다.');for(const [key,a] of Object.entries(data.accounts||{})){if(!a.id)errors.push(`${key} 계좌 ID가 없습니다.`);for(const h of a.holdings||[])if(!h.id||Number(h.qty)<0||Number(h.value)<0||Number(h.cost)<0)errors.push(`${key} 보유상품 데이터를 확인하세요.`)}const ids=(data.ledger||[]).map(r=>r.id).filter(Boolean);if(new Set(ids).size!==ids.length)errors.push('중복 원장 ID가 있습니다.');return {ok:!errors.length,errors,counts:counts(data)}}
async function buildDataBackup(source=state){const valid=validateData(source);if(!valid.ok)throw new Error(valid.errors[0]);const files=backupFiles(source),checksums={};for(const [name,content] of Object.entries(files))checksums[name]=await sha256(content);const manifest={appId:APP_ID,appVersion:APP_VERSION,schemaVersion:SCHEMA_VERSION,backupFormatVersion:'2.0',createdAt:isoNow(),counts:counts(source),files:Object.keys(files),checksums,validation:'passed'};files['manifest.json']=JSON.stringify(manifest,null,2);const bytes=zipCreate(files),verified=await verifyDataBackup(bytes);if(!verified.ok)throw new Error(verified.errors[0]);return {bytes,blob:new Blob([bytes],{type:'application/zip'}),manifest,fileName:`PENSION_DATA_${fileStamp()}.zip`}}
async function verifyDataBackup(bytes){const errors=[];try{const files=zipRead(bytes);for(const name of DATA_REQUIRED)if(!files[name])errors.push(`필수 파일 누락: ${name}`);if(errors.length)return {ok:false,errors};const manifest=JSON.parse(dec.decode(files['manifest.json'])),envelope=JSON.parse(dec.decode(files['full-backup.json']));if(manifest.appId!==APP_ID||envelope.appId!==APP_ID)errors.push('다른 앱의 백업입니다.');for(const [name,hash] of Object.entries(manifest.checksums||{})){if(!files[name]){errors.push(`체크섬 파일 누락: ${name}`);continue}if(await sha256(files[name])!==hash)errors.push(`체크섬 불일치: ${name}`)}const data=ensureSchema6(envelope.data),valid=validateData(data);errors.push(...valid.errors);return {ok:!errors.length,errors,manifest,data,files}}catch(e){return {ok:false,errors:[e.message]}}}
async function buildProjectBackup(){const dataBackup=await buildDataBackup(state),files={},checksums={};for(const name of PROJECT_ASSETS){const res=await fetch(name,{cache:'no-store'});if(!res.ok)throw new Error(`앱 파일을 읽지 못했습니다: ${name}`);files[name]=new Uint8Array(await res.arrayBuffer());checksums[name]=await sha256(files[name])}files['data/pension-data.zip']=dataBackup.bytes;checksums['data/pension-data.zip']=await sha256(dataBackup.bytes);files['RECOVERY.md']=enc.encode('# 개인연금 프로젝트 전체 백업\n\n앱 배포 서비스가 변경되면 이 ZIP의 앱 파일을 새 정적 호스팅에 올리고, 앱에서 data/pension-data.zip을 복원하세요.\n');checksums['RECOVERY.md']=await sha256(files['RECOVERY.md']);const manifest={projectBackupFormatVersion:'2.0',appId:APP_ID,appVersion:APP_VERSION,schemaVersion:SCHEMA_VERSION,createdAt:isoNow(),appFiles:PROJECT_ASSETS,dataFile:'data/pension-data.zip',checksums,validation:'passed'};files['project-manifest.json']=enc.encode(JSON.stringify(manifest,null,2));const bytes=zipCreate(files),verified=await verifyProjectBackup(bytes);if(!verified.ok)throw new Error(verified.errors[0]);return {bytes,blob:new Blob([bytes],{type:'application/zip'}),manifest,fileName:`PENSION_PROJECT_${fileStamp()}.zip`}}
async function verifyProjectBackup(bytes){const errors=[];try{const files=zipRead(bytes),manifest=JSON.parse(dec.decode(files['project-manifest.json']||new Uint8Array()));if(manifest.appId!==APP_ID)errors.push('다른 앱의 프로젝트 백업입니다.');for(const name of PROJECT_ASSETS)if(!files[name])errors.push(`앱 파일 누락: ${name}`);for(const [name,hash] of Object.entries(manifest.checksums||{}))if(!files[name]||await sha256(files[name])!==hash)errors.push(`프로젝트 체크섬 오류: ${name}`);const inner=files[manifest.dataFile||'data/pension-data.zip'];if(!inner)errors.push('내부 데이터 ZIP이 없습니다.');const dataVerification=inner?await verifyDataBackup(inner):null;if(dataVerification&&!dataVerification.ok)errors.push(...dataVerification.errors);return {ok:!errors.length,errors,manifest,files,dataVerification}}catch(e){return {ok:false,errors:[e.message]}}}
function fileStamp(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`}
async function saveBlob(blob,fileName,{share=false}={}){if(share&&navigator.share&&navigator.canShare?.({files:[new File([blob],fileName,{type:'application/zip'})]})){await navigator.share({files:[new File([blob],fileName,{type:'application/zip'})],title:'개인연금 프로젝트 백업'});return '공유 대상'}if(window.showSaveFilePicker){const handle=await showSaveFilePicker({suggestedName:fileName,types:[{description:'ZIP 백업',accept:{'application/zip':['.zip']}}]}),w=await handle.createWritable();await w.write(blob);await w.close();return '선택한 폴더'}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=fileName;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);return '다운로드 폴더'}
function result(title,body,error=false){const el=document.getElementById('backupResult');if(!el)return;el.className=`backupResult open ${error?'error':''}`;el.innerHTML=`<b>${esc(title)}</b><p>${body}</p>`}
function refreshDataCenter(){const el=document.getElementById('dataBody');if(!el||!document.getElementById('dataSheet').classList.contains('open'))return;renderDataCenter()}
function renderDataCenter(){const s=state.meta.storage||{},c=counts(state);document.getElementById('dataBody').innerHTML=`<div class="sheetNotice">폰 데이터 ZIP은 자주, 프로젝트 전체 ZIP은 배포 서비스 변경에 대비해 Google Drive에 보관합니다.</div><div class="storageGrid"><div class="storageCard"><b>이 휴대폰</b><span>${esc(s.localStatus||'대기')}</span><small>${esc(s.lastLocalSave||'저장 기록 없음')}</small></div><div class="storageCard"><b>클라우드 원본</b><span>${esc(s.cloudStatus||'연결 전')}</span><small>Firebase 연결 전</small></div><div class="storageCard"><b>Google Drive</b><span>${esc(s.driveStatus||'연결 전')}</span><small>공유 저장 방식</small></div></div><button class="dataLaunch" id="phoneBackup"><span><b>폰에 데이터 ZIP 백업</b><small>계좌 ${c.accounts}개 · 기록 ${c.transactions}건 · 앱 코드 제외</small></span><span>↓</span></button><button class="dataLaunch" id="projectBackup"><span><b>Google Drive에 프로젝트 전체 백업</b><small>앱 ${PROJECT_ASSETS.length}개 + 현재 데이터</small></span><span>›</span></button><label class="dataLaunch fileLaunch"><span><b>백업 파일 불러오기</b><small>ZIP 또는 JSON 검사 후 미리보기</small></span><span>›</span><input id="restoreFile" type="file" accept=".zip,.json,application/zip,application/json" hidden></label><button class="dataLaunch" id="pasteRestore"><span><b>JSON 텍스트 붙여넣기</b><small>파일이 없어도 복원</small></span><span>›</span></button><div id="backupResult" class="backupResult"></div><div id="restorePreview"></div><div class="dataVersion">앱 ${APP_VERSION} · 데이터 구조 ${SCHEMA_VERSION} · 사진 원본 미저장</div>`;document.getElementById('phoneBackup').onclick=phoneBackup;document.getElementById('projectBackup').onclick=projectBackup;document.getElementById('restoreFile').onchange=e=>readRestoreFile(e.target.files?.[0]);document.getElementById('pasteRestore').onclick=()=>{const text=prompt('full-backup.json 또는 표준 JSON을 붙여넣으세요.');if(text)readRestoreText(text)}}
function openDataCenter(){renderDataCenter();openSheet('dataSheet')}
async function phoneBackup(){try{result('백업 생성 중','원본과 ZIP을 다시 검사합니다.');const b=await buildDataBackup(state),where=await saveBlob(b.blob,b.fileName);state.meta.storage.lastBackup=new Date().toLocaleString('ko-KR');state.meta.storage.lastValidation='정상';saveState({quiet:true});result('데이터 백업 완료',`${esc(b.fileName)}<br>${where} · 기록 ${b.manifest.counts.transactions}건 · 검증 정상`)}catch(e){result('백업 실패',esc(e.message),true)}}
async function projectBackup(){try{result('프로젝트 백업 생성 중','앱 파일과 현재 데이터의 체크섬을 검사합니다.');const b=await buildProjectBackup(),where=await saveBlob(b.blob,b.fileName,{share:true});state.meta.storage.driveStatus=where==='공유 대상'?'공유 완료':'파일 생성 완료';state.meta.storage.lastDriveBackup=new Date().toLocaleString('ko-KR');saveState({quiet:true});result('프로젝트 전체 백업 완료',`${esc(b.fileName)}<br>${where} · 앱 ${PROJECT_ASSETS.length}개 + 데이터 · 검증 정상`)}catch(e){result('프로젝트 백업 실패',esc(e.message),true)}}
async function readRestoreFile(file){if(!file)return;try{result('백업 검사 중',esc(file.name));const bytes=new Uint8Array(await file.arrayBuffer());if(file.name.toLowerCase().endsWith('.zip')||(bytes[0]===0x50&&bytes[1]===0x4b)){const files=zipRead(bytes);if(files['project-manifest.json']){const p=await verifyProjectBackup(bytes);if(!p.ok)throw new Error(p.errors[0]);restoreCandidate={data:p.dataVerification.data,manifest:p.dataVerification.manifest,source:'project'}}else{const v=await verifyDataBackup(bytes);if(!v.ok)throw new Error(v.errors[0]);restoreCandidate={data:v.data,manifest:v.manifest,source:'data'}}}else{const parsed=JSON.parse(dec.decode(bytes)),data=parsed.data||parsed;restoreCandidate={data:ensureSchema6(data),manifest:{appVersion:parsed.appVersion||data.meta?.appVersion,schemaVersion:parsed.schemaVersion||data.schemaVersion,createdAt:parsed.createdAt||data.meta?.updatedAt,counts:counts(data)},source:'json'}}renderRestorePreview()}catch(e){restoreCandidate=null;result('복원 파일 거부',esc(e.message),true)}}
function readRestoreText(text){try{const parsed=JSON.parse(text),data=parsed.data||parsed;restoreCandidate={data:ensureSchema6(data),manifest:{appVersion:parsed.appVersion||data.meta?.appVersion,schemaVersion:parsed.schemaVersion||data.schemaVersion,createdAt:parsed.createdAt||data.meta?.updatedAt,counts:counts(data)},source:'text'};renderRestorePreview()}catch(e){result('JSON 검사 실패',esc(e.message),true)}}
function renderRestorePreview(){if(!restoreCandidate)return;try{const data=ensureSchema6(clone(restoreCandidate.data)),valid=validateData(data);if(!valid.ok)throw new Error(valid.errors[0]);restoreCandidate.data=data;const c=counts(data),el=document.getElementById('restorePreview');el.innerHTML=`<div class="restorePreview open"><h4>복원 미리보기</h4><div class="previewGrid"><div class="previewCell"><small>앱 버전</small><b>${esc(restoreCandidate.manifest?.appVersion||data.meta?.appVersion||'-')}</b></div><div class="previewCell"><small>데이터 구조</small><b>${data.schemaVersion} → ${SCHEMA_VERSION}</b></div><div class="previewCell"><small>계좌·상품</small><b>${c.accounts}개 · ${c.holdings}개</b></div><div class="previewCell"><small>기록·스냅샷</small><b>${c.transactions}건 · ${c.snapshots}건</b></div><div class="previewCell"><small>총자산</small><b>${man(c.totalAssets)}</b></div><div class="previewCell"><small>검사</small><b class="good">정상</b></div></div><div class="restoreButtons"><button class="btn" id="cancelRestore">취소</button><button class="btn primary" id="applyRestore">안전백업 후 복원</button></div></div>`;document.getElementById('cancelRestore').onclick=()=>{restoreCandidate=null;el.innerHTML=''};document.getElementById('applyRestore').onclick=applyRestore;result('복원 가능','아직 현재 데이터는 변경하지 않았습니다.')}catch(e){restoreCandidate=null;result('복원 데이터 거부',esc(e.message),true)}}
async function applyRestore(){if(!restoreCandidate?.data)return;const original=clone(state);try{const safety=await buildDataBackup(original);try{await dbPut(SAFETY,{createdAt:isoNow(),data:original,bytes:safety.bytes})}catch{localStorage.setItem(`${STORAGE_KEY}-safety`,JSON.stringify(original))}state=ensureSchema6(clone(restoreCandidate.data));state.meta.storage.lastRestore=new Date().toLocaleString('ko-KR');saveState({quiet:true});await persist(clone(state));restoreCandidate=null;renderAll(true);renderDataCenter();result('복원 완료',`현재 데이터로 교체했습니다. 총자산 ${man(totalAsset())}`)}catch(e){state=original;saveState({quiet:true});renderAll(true);result('복원 실패 · 기존 데이터 유지',esc(e.message),true)}}
window.PensionStorage={persist,hydrate,dbPut,dbGet};
window.PensionBackup={PROJECT_ASSETS,buildDataBackup,verifyDataBackup,buildProjectBackup,verifyProjectBackup,validateData,counts,openDataCenter,refreshDataCenter,zipCreate,zipRead,sha256};
})();
