/* 개인연금 V2.0 RC6 - 입력·설정 */
'use strict';
let toastTimer=null,settingsDraft=null,monthPickerValue=CURRENT_MONTH_KEY;
function toast(message){const el=document.getElementById('toast');if(!el)return;clearTimeout(toastTimer);el.textContent=message;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function openSheet(id){const el=document.getElementById(id);if(!el)return;el.classList.add('open');document.body.classList.add('sheetOpen');el.querySelector('.sheet')?.scrollTo(0,0)}
function closeSheet(id){const el=document.getElementById(id);if(!el)return;el.classList.remove('open');if(!document.querySelector('.overlay.open'))document.body.classList.remove('sheetOpen');window.PensionOCR?.cleanup?.()}
function confirmAction(title,body,onConfirm){const t=document.getElementById('formTitle'),b=document.getElementById('formBody');t.textContent=title;b.innerHTML=`<div class="settingsInfo">${esc(body)}</div><div class="confirmButtons"><button class="btn" id="confirmCancel">취소</button><button class="btn primary" id="confirmOk">확인</button></div>`;openSheet('formSheet');document.getElementById('confirmCancel').onclick=()=>closeSheet('formSheet');document.getElementById('confirmOk').onclick=()=>{closeSheet('formSheet');onConfirm?.()}}
function moneyInput(id,label,value,hint=''){return `<div class="field"><label>${esc(label)}</label><input id="${id}" type="text" inputmode="numeric" value="${Number(value||0).toLocaleString('ko-KR')}">${hint?`<div class="fieldHint">${esc(hint)}</div>`:''}</div>`}
function bindMoneyInput(id){const input=document.getElementById(id);if(!input)return;input.addEventListener('blur',()=>{const n=parseMoney(input.value);input.value=n?Number(n).toLocaleString('ko-KR'):''})}
function openMonthPicker(current,onSelect){
  monthPickerValue=current||CURRENT_MONTH_KEY;let [year,month]=monthPickerValue.split('-').map(Number);let overlay=document.getElementById('monthPicker');if(!overlay){overlay=document.createElement('div');overlay.id='monthPicker';overlay.className='overlay monthPickerOverlay';document.body.appendChild(overlay)}
  const paint=()=>{overlay.innerHTML=`<div class="monthPickerCard"><div class="monthPickerHead"><button id="monthPrev">‹</button><b>${year}년</b><button id="monthNext" ${year>=CURRENT_YEAR?'disabled':''}>›</button></div><div class="monthGrid">${Array.from({length:12},(_,i)=>{const m=i+1,key=`${year}-${String(m).padStart(2,'0')}`,future=key>CURRENT_MONTH_KEY;return `<button data-month="${key}" class="${key===monthPickerValue?'active':''}" ${future?'disabled':''}>${m}월</button>`}).join('')}</div><div class="monthPickerActions"><button class="btn" id="monthCancel">취소</button></div></div>`;overlay.classList.add('open');document.body.classList.add('sheetOpen');document.getElementById('monthPrev').onclick=()=>{year--;paint()};document.getElementById('monthNext').onclick=()=>{if(year<CURRENT_YEAR){year++;paint()}};document.getElementById('monthCancel').onclick=()=>{overlay.classList.remove('open');if(!document.querySelector('.overlay.open'))document.body.classList.remove('sheetOpen')};overlay.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{monthPickerValue=b.dataset.month;overlay.classList.remove('open');onSelect(monthPickerValue)})};paint();
}
function renderContributionForm(){
  const title=document.getElementById('formTitle'),body=document.getElementById('formBody');title.textContent='이번 달 납입';let selectedMonth=CURRENT_MONTH_KEY;
  const paint=()=>{const status=currentContributionStatus(selectedMonth);body.innerHTML=`<button class="monthSelect" id="contributionMonth"><span>기록 월</span><b>${monthLabel(selectedMonth)}</b><span>›</span></button><div class="settingsInfo">과거 달은 현재 잔고를 바꾸지 않고 납입 확인 이력만 남깁니다.</div><div class="contributionAccounts">${['pension','irp'].map(key=>`<label class="contributionAccount ${status[key]?'done':''}"><input type="checkbox" id="use-${key}" ${status[key]?'disabled':'checked'}><span><b>${ACCOUNT_LABEL[key]}</b><small>${status[key]?'이미 기록됨':'계획 '+man(state.settings.monthly[key])}</small></span><input id="amount-${key}" inputmode="numeric" value="${Number(state.settings.monthly[key]).toLocaleString('ko-KR')}" ${status[key]?'disabled':''}></label>`).join('')}</div><fieldset class="rc6Choice"><legend>금액 변경 시</legend><label><input type="radio" name="planMode" value="once" checked> 이번 달만 변경</label><label><input type="radio" name="planMode" value="future"> 앞으로의 월 계획도 변경</label></fieldset><div id="formError" class="error"></div><button class="btn primary full" id="saveContribution">선택 계좌 기록</button>`;
    document.getElementById('contributionMonth').onclick=()=>openMonthPicker(selectedMonth,key=>{selectedMonth=key;paint()});['pension','irp'].forEach(key=>bindMoneyInput(`amount-${key}`));document.getElementById('saveContribution').onclick=()=>{const mode=document.querySelector('input[name=planMode]:checked')?.value||'once',selected=['pension','irp'].filter(k=>document.getElementById(`use-${k}`)?.checked),error=document.getElementById('formError');if(!selected.length){error.textContent='기록할 계좌를 선택하세요.';return}try{for(const key of selected){const amount=parseMoney(document.getElementById(`amount-${key}`).value);addContribution({accountKey:key,amount,monthKey:selectedMonth});if(mode==='future')state.settings.monthly[key]=amount}saveState({quiet:true});closeSheet('formSheet');renderAll(true);toast(`${monthLabel(selectedMonth)} 납입을 기록했어요`)}catch(e){error.textContent=e.message}};
  };paint();
}
function parseHoldingText(text){
  return String(text||'').split(/\r?\n/).map((line,index)=>{const parts=line.split(/[|\t]/).map(s=>s.trim());if(parts.length<3)return null;const [name,qty,value,cost,className]=parts;return {line:index+1,name,qty:parseMoney(qty),value:parseMoney(value),cost:parseMoney(cost)||parseMoney(value),className:className||'',class:state.settings.assetClasses.find(c=>c.name===className||c.id===className)?.id||'growth'}}).filter(Boolean);
}
function renderManualSnapshot(){
  const title=document.getElementById('formTitle'),body=document.getElementById('formBody');title.textContent='자산현황 갱신';body.innerHTML=`<div class="snapshotMode"><button id="photoMode" class="btn primary">사진 자동 인식</button><span>또는</span><b>텍스트 붙여넣기</b></div><div class="field"><label>계좌</label><select id="snapAccount"><option value="pension">연금저축</option><option value="irp">IRP</option></select></div>${moneyInput('snapTotal','계좌 전체 총액 · 선택',0,'예수금이 있으면 입력하세요. 차이는 현금으로 반영합니다.')}<div class="field"><label>종목 표</label><textarea id="snapText" rows="8" placeholder="종목명 | 수량 | 평가금액 | 원금 | 자산군\nRISE 미국나스닥100 | 176 | 14,000,000 | 10,800,000 | 성장주"></textarea></div><div class="settingsInfo" id="snapPreview">붙여넣으면 반영 전에 합계와 오류를 확인합니다.</div><div id="formError" class="error"></div><button class="btn primary full" id="applySnapshot">검토 후 반영</button>`;bindMoneyInput('snapTotal');document.getElementById('photoMode').onclick=()=>window.PensionOCR?.render?.();const preview=()=>{const rows=parseHoldingText(document.getElementById('snapText').value),sum=rows.reduce((s,r)=>s+r.value,0),total=parseMoney(document.getElementById('snapTotal').value)||sum,dupes=rows.length-new Set(rows.map(r=>r.name)).size;document.getElementById('snapPreview').innerHTML=`<b>${rows.length}개 상품</b><div class="previewList"><div class="previewItem"><span>상품 평가금 합계</span><b>${fmt(sum)}</b></div><div class="previewItem"><span>현금 반영</span><b class="${total<sum?'bad':''}">${fmt(total-sum)}</b></div>${dupes?`<div class="previewItem"><span>중복</span><b class="bad">${dupes}개</b></div>`:''}</div>`};document.getElementById('snapText').addEventListener('input',preview);document.getElementById('snapTotal').addEventListener('input',preview);preview();document.getElementById('applySnapshot').onclick=()=>{const rows=parseHoldingText(document.getElementById('snapText').value),total=parseMoney(document.getElementById('snapTotal').value),error=document.getElementById('formError');try{if(!rows.length&&!total)throw new Error('계좌 총액이나 종목 표를 입력하세요.');if(!rows.length){const key=document.getElementById('snapAccount').value,a=state.accounts[key],sum=a.holdings.reduce((s,h)=>s+h.value,0);if(total<sum)throw new Error('계좌 총액이 기존 상품 합계보다 작습니다.');a.cash=total-sum;state.lastUpdated=`${CURRENT_YEAR}.${String(CURRENT_MONTH).padStart(2,'0')}.${String(now.getDate()).padStart(2,'0')}`;saveState({quiet:true})}else applySnapshot(document.getElementById('snapAccount').value,rows,total,{source:'snapshot-text'});closeSheet('formSheet');renderAll(true);toast('자산현황을 갱신했어요')}catch(e){error.textContent=e.message}};
}
function renderDetailForm(){
  const title=document.getElementById('formTitle'),body=document.getElementById('formBody');title.textContent='배당·매도 기록';const today=new Date().toISOString().slice(0,10);body.innerHTML=`<div class="segment two detailType"><i class="segmentIndicator"></i><button data-detail-type="dividend" class="active">배당·분배금</button><button data-detail-type="sell">매도 손익</button></div><div class="field"><label>계좌</label><select id="detailAccount"><option value="pension">연금저축</option><option value="irp">IRP</option></select></div><div class="field"><label>상품</label><select id="detailAsset"></select></div><div class="field"><label>날짜</label><input id="detailDate" type="date" max="${today}" value="${today}"></div><div id="detailAmountWrap">${moneyInput('detailAmount','배당·분배금',0)}</div><div id="detailRealizedWrap" hidden>${moneyInput('detailRealized','매도 확정손익',0,'손실은 - 금액으로 입력')}</div><div class="field"><label>메모 · 선택</label><input id="detailNote" maxlength="80"></div><div id="formError" class="error"></div><button class="btn primary full" id="saveDetail">기록 저장</button>`;let type='dividend';const fillAssets=()=>{const key=document.getElementById('detailAccount').value;document.getElementById('detailAsset').innerHTML=`<option value="">계좌 전체</option>${state.accounts[key].holdings.map(h=>`<option value="${esc(h.id)}">${esc(h.name)}</option>`).join('')}`};fillAssets();document.getElementById('detailAccount').onchange=fillAssets;document.querySelectorAll('[data-detail-type]').forEach(b=>b.onclick=()=>{type=b.dataset.detailType;document.querySelectorAll('[data-detail-type]').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('.detailType .segmentIndicator').classList.toggle('right',type==='sell');document.getElementById('detailAmountWrap').hidden=type!=='dividend';document.getElementById('detailRealizedWrap').hidden=type!=='sell'});bindMoneyInput('detailAmount');bindMoneyInput('detailRealized');document.getElementById('saveDetail').onclick=()=>{const key=document.getElementById('detailAccount').value,assetId=document.getElementById('detailAsset').value,h=state.accounts[key].holdings.find(x=>x.id===assetId),error=document.getElementById('formError');try{addCashflow({type,accountKey:key,assetId,assetName:h?.name||'',amount:parseMoney(document.getElementById('detailAmount').value),realized:parseMoney(document.getElementById('detailRealized').value),date:document.getElementById('detailDate').value,note:document.getElementById('detailNote').value});closeSheet('formSheet');renderAll(true);toast('기록을 저장했어요')}catch(e){error.textContent=e.message}};
}
function openRecordEditor(id){
  const r=state.ledger.find(x=>x.id===id);if(!r)return;if(r.synthetic)return toast('이전 데이터 보정 기록은 상세에서만 확인할 수 있어요');const title=document.getElementById('formTitle'),body=document.getElementById('formBody');title.textContent='기록 수정';body.innerHTML=`<div class="settingsInfo">기록 ID는 유지되고, 삭제는 취소 이력으로 보관됩니다.</div><div class="field"><label>날짜</label><input id="editDate" type="date" max="${new Date().toISOString().slice(0,10)}" value="${String(r.date).slice(0,10)}"></div>${moneyInput('editAmount',r.type==='sell'?'확정손익':'금액',r.type==='sell'?r.realized:r.amount)}<div class="field"><label>메모</label><input id="editNote" value="${esc(r.note||'')}"></div><div id="formError" class="error"></div><div class="recordActions"><button class="btn danger" id="cancelRecord">기록 취소</button><button class="btn primary" id="updateRecord">수정 저장</button></div>`;bindMoneyInput('editAmount');openSheet('formSheet');document.getElementById('updateRecord').onclick=()=>{try{const date=document.getElementById('editDate').value,changes={date:`${date}T12:00:00.000Z`,monthKey:date.slice(0,7),year:Number(date.slice(0,4)),note:document.getElementById('editNote').value};if(r.type==='sell')changes.realized=parseMoney(document.getElementById('editAmount').value);else changes.amount=parseMoney(document.getElementById('editAmount').value);updateLedgerRecord(id,changes);closeSheet('formSheet');renderAll(true);toast('기록을 수정했어요')}catch(e){document.getElementById('formError').textContent=e.message}};document.getElementById('cancelRecord').onclick=()=>confirmAction('기록을 취소할까요?','원장에서 지우지 않고 취소 이력으로 보관합니다.',()=>{try{cancelLedgerRecord(id);renderAll(true);toast('기록을 취소했어요')}catch(e){toast(e.message)}});
}
function renderHistoryManager(){
  const title=document.getElementById('formTitle'),body=document.getElementById('formBody');title.textContent='과거 연도 요약';const rows=performanceSeries('all');body.innerHTML=`<div class="sheetNotice">과거 성과를 보기 위한 고급 입력입니다. 한 줄에 연도 | 연말자산 | 누적순납입 | 배당을 입력하세요.</div><details class="card rc6HistoryList" open><summary>현재 ${rows.length}개 연도</summary>${rows.slice().reverse().map(r=>`<div class="r5Milestone"><span>${r.year}</span><b>${man(r.end)}</b><small>누적 ${man(r.cumulative)}</small></div>`).join('')}</details><div class="field"><label>여러 연도 붙여넣기</label><textarea id="historyText" rows="9" placeholder="2024 | 36,800,000 | 30,900,000 | 470,000"></textarea></div><div id="formError" class="error"></div><button class="btn primary full" id="saveHistory">전체 흐름 검사 후 반영</button>`;document.getElementById('saveHistory').onclick=()=>{const parsed=String(document.getElementById('historyText').value).split(/\r?\n/).filter(Boolean).map((line,i)=>{const p=line.split(/[|\t]/).map(x=>x.trim());return {line:i+1,year:Number(p[0]),end:parseMoney(p[1]),cumulative:parseMoney(p[2]),dividend:parseMoney(p[3])}}),error=document.getElementById('formError');try{if(!parsed.length)throw new Error('입력한 연도가 없습니다.');let prev=-1;for(const r of parsed){if(!Number.isInteger(r.year)||r.year>CURRENT_YEAR)throw new Error(`${r.line}번째 연도를 확인하세요.`);if(r.cumulative<prev)throw new Error('누적 순납입이 뒤로 감소합니다.');prev=r.cumulative}for(const r of parsed){const old=state.years[r.year]||{},previous=state.years[r.year-1];const start=Number(old.start??previous?.end??0),contribution=Math.max(0,r.cumulative-Number(previous?.cumulative||0)),profit=r.end-start-contribution;state.years[r.year]={...old,start,end:r.end,cumulative:r.cumulative,contribution,operating:r.end-r.cumulative,dividend:r.dividend,return:profit/Math.max(1,start+contribution/2)*100,monthly:old.monthly||Array(12).fill(0),accountContribution:old.accountContribution||{pension:Math.round(contribution*2/3),irp:Math.round(contribution/3)}}}saveState({quiet:true});closeSheet('formSheet');renderAll(true);toast('과거 연도 흐름을 반영했어요')}catch(e){error.textContent=e.message}};
}
function openForm(type){closeSheet('quickSheet');openSheet('formSheet');if(type==='contribution')renderContributionForm();else if(type==='snapshot')renderManualSnapshot();else if(type==='detail')renderDetailForm();else if(type==='history')renderHistoryManager()}
function renderSettings(){
  settingsDraft=clone({profile:state.profile,settings:state.settings});const body=document.getElementById('settingsBody');body.innerHTML=`<div class="sheetNotice">자주 쓰는 계획만 먼저 보이고, 계산 가정과 데이터 관리는 접어두었습니다.</div><section class="settingsSection"><div class="settingsTitle">기본 계획</div><div class="twoFields"><div class="field"><label>출생연도</label><input id="setBirthYear" type="number" value="${settingsDraft.profile.birthYear}"><div class="fieldHint">출생연도 기준 나이는 매년 자동으로 올라갑니다.</div></div><div class="field"><label>연금 개시 나이</label><input id="setRetAge" type="number" value="${settingsDraft.profile.retirementAge}"></div></div>${moneyInput('setGoal','목표 개인연금 월인출액',settingsDraft.settings.goalMonthly,'현재 돈 가치 기준')}</section><section class="settingsSection"><div class="settingsTitle">월 납입 계획</div>${moneyInput('setPension','연금저축',settingsDraft.settings.monthly.pension)}${moneyInput('setIrp','IRP',settingsDraft.settings.monthly.irp)}<div class="settingsInfo">2026년 앱 설정 기준: 연금저축 세액공제 대상 최대 연 600만원, 연금저축·IRP 합산 최대 연 900만원입니다. 실제 공제는 소득과 제도 변경에 따라 달라질 수 있습니다.</div></section><details class="settingsSection"><summary class="settingsTitle">미래 계산 가정</summary><div class="twoFields"><div class="field"><label>적립 기대수익률</label><input id="setReturn" type="number" step="0.1" value="${settingsDraft.settings.returnRate}"></div><div class="field"><label>물가상승률</label><input id="setInflation" type="number" step="0.1" value="${settingsDraft.settings.inflation}"></div><div class="field"><label>수령 기간</label><input id="setWithdrawYears" type="number" value="${settingsDraft.settings.withdrawYears}"></div><div class="field"><label>수령 중 수익률</label><input id="setWithdrawReturn" type="number" step="0.1" value="${settingsDraft.settings.withdrawReturn}"></div></div></details><details class="settingsSection"><summary class="settingsTitle">자산군 목표 비중</summary><div id="classRows">${settingsDraft.settings.assetClasses.map((c,i)=>`<div class="classRow"><input data-class-name="${i}" value="${esc(c.name)}"><input data-class-target="${i}" type="number" value="${c.target}"><span>%</span></div>`).join('')}</div><div id="targetSum" class="fieldHint"></div></details><section class="settingsSection"><div class="settingsTitle">데이터와 고급 관리</div><button class="dataLaunch" id="openDataCenter"><span><b>백업·복원·저장 상태</b><small>폰 데이터 ZIP과 프로젝트 전체 ZIP</small></span><span>›</span></button><button class="dataLaunch" id="openHistory"><span><b>과거 연도 요약</b><small>장기 성과를 위한 고급 입력</small></span><span>›</span></button></section><div id="settingsError" class="error"></div><div class="saveBar"><button class="btn primary full" id="saveSettings">설정 저장</button></div>`;
  ['setGoal','setPension','setIrp'].forEach(bindMoneyInput);const updateSum=()=>{const sum=[...document.querySelectorAll('[data-class-target]')].reduce((s,x)=>s+Number(x.value||0),0);document.getElementById('targetSum').textContent=`합계 ${sum}% ${Math.abs(sum-100)<.01?'· 정상':'· 100%로 맞춰주세요'}`};document.querySelectorAll('[data-class-target]').forEach(x=>x.oninput=updateSum);updateSum();document.getElementById('openDataCenter').onclick=()=>{closeSheet('settingsSheet');window.PensionBackup?.openDataCenter?.()};document.getElementById('openHistory').onclick=()=>{closeSheet('settingsSheet');openForm('history')};document.getElementById('saveSettings').onclick=()=>{const error=document.getElementById('settingsError');try{const birth=Number(document.getElementById('setBirthYear').value),age=CURRENT_YEAR-birth,ret=Number(document.getElementById('setRetAge').value);if(!Number.isInteger(birth)||age<10||age>100)throw new Error('출생연도를 확인하세요.');if(ret<=age||ret>90)throw new Error('연금 개시 나이를 확인하세요.');const targets=[...document.querySelectorAll('[data-class-target]')].map(x=>Number(x.value)||0),sum=targets.reduce((s,n)=>s+n,0);if(Math.abs(sum-100)>.01)throw new Error('자산군 목표 비중 합계를 100%로 맞추세요.');state.profile.birthYear=birth;state.profile.age=age;state.profile.retirementAge=ret;state.settings.goalMonthly=parseMoney(document.getElementById('setGoal').value);state.settings.monthly.pension=parseMoney(document.getElementById('setPension').value);state.settings.monthly.irp=parseMoney(document.getElementById('setIrp').value);state.settings.returnRate=Number(document.getElementById('setReturn').value);state.settings.inflation=Number(document.getElementById('setInflation').value);state.settings.withdrawYears=Number(document.getElementById('setWithdrawYears').value);state.settings.withdrawReturn=Number(document.getElementById('setWithdrawReturn').value);state.settings.assetClasses.forEach((c,i)=>{c.name=document.querySelector(`[data-class-name="${i}"]`).value.trim()||c.name;c.target=targets[i]});saveState({quiet:true});closeSheet('settingsSheet');renderAll(true);toast('설정을 저장했어요')}catch(e){error.textContent=e.message}};
}
function openSettings(section=''){renderSettings();openSheet('settingsSheet');if(section==='future')setTimeout(()=>document.querySelector('#settingsBody details')?.scrollIntoView({behavior:'smooth'}),180)}
window.PensionForms={toast,openSheet,closeSheet,confirmAction,openMonthPicker,openForm,openRecordEditor,renderSettings,openSettings,parseHoldingText,bindMoneyInput};
