/* 개인연금 V2.0 RC6 - OCR 입력 */
'use strict';
(()=>{
let objectUrl=null,fileRef=null,rows=[];
const moneyToken=/[-+]?\d[\d,]*(?:\.\d+)?%?/g;
const numToken=v=>Number(String(v||'').replace(/[%+,\s]/g,''))||0;
const cleanLine=s=>String(s||'').replace(/[·•ㆍ]/g,' ').replace(/[“”‘’]/g,'').replace(/\s+/g,' ').trim();
function numericTokens(line){const out=[];for(const m of line.matchAll(moneyToken))out.push({raw:m[0],value:numToken(m[0]),index:m.index});return out}
function normalizeFundName(raw){
  let s=cleanLine(raw).replace(/^[^A-Za-z가-힣0-9]+/,'').replace(/\b현금\b/g,'').trim(),c=s.replace(/\s/g,'').toUpperCase();
  if(/글로벌반도/.test(c)&&(/PLUS/.test(c)||/(TOP4|1064|10P4|17004)/.test(c)))return 'ACE 글로벌반도체TOP4 Plus';
  if(/미국나스/.test(c)&&/(닥|DAK)?100/.test(c))return 'RISE 미국나스닥100';
  if(/다우존스/.test(c)&&(/미국배/.test(c)||/KODEX/.test(c)))return 'KODEX 미국배당다우존스';
  if(/머니마켓/.test(c)||/켓액티브/.test(c))return 'KODEX 머니마켓액티브';
  if(/전력핵심인프라/.test(c))return 'KODEX 미국AI전력핵심인프라';
  return s.replace(/^K[0O]D[E3]X/i,'KODEX').replace(/^R[|I1]SE/i,'RISE').replace(/^A[C0]E/i,'ACE').slice(0,60);
}
function guessClass(name){const n=String(name).toLowerCase();if(/배당|다우존스/.test(n))return 'dividend';if(/머니마켓|채권|국채|단기금리|mmf/.test(n))return 'bond';if(/금|gold/.test(n))return 'gold';return 'growth'}
function parseBrokerOcr(text){
  const lines=String(text||'').split(/\r?\n/).map(cleanLine).filter(Boolean),out=[];let buffer=[],pending=null;
  const noise=/종목명|평가손익|수익률|평가금액|매입단가|현재가|실시간|보유잔고|주식 잔고|메뉴|주문|이체|지수|국내|해외|KRX|구분/;
  for(const line of lines){
    if(noise.test(line)){if(!pending)buffer=[];continue}const tokens=numericTokens(line),hasPct=/%/.test(line);
    if(!pending&&!hasPct&&tokens.length>=3){const last=tokens.slice(-3),profit=last[0].value,qty=last[1].value,avg=last[2].value,prefix=line.slice(0,last[0].index).trim(),name=normalizeFundName([...buffer,prefix].join(' '));if(name&&qty>=0&&qty<1e7&&Math.abs(profit)<1e10&&avg>=0){pending={name,profit,qty,avg};buffer=[];continue}}
    if(pending&&(hasPct||/현금/.test(line))&&tokens.length>=2){const last=tokens.slice(-2),value=last[0].value,current=last[1].value,cost=value-pending.profit;if(value>=0&&current>=0&&cost>=0)out.push({name:pending.name,qty:pending.qty,value,cost,profit:pending.profit,class:guessClass(pending.name),confidence:/^(ACE|RISE|KODEX|TIGER|SOL|PLUS|HANARO|KIWOOM|TIMEFOLIO)\b/.test(pending.name)?96:80});pending=null;buffer=[];continue}
    if(!pending&&!hasPct&&!/현금/.test(line)&&tokens.length<3&&/[A-Za-z가-힣]/.test(line))buffer.push(line);
  }
  return out.filter((r,i,a)=>a.findIndex(x=>x.name===r.name&&x.value===r.value)===i);
}
async function preprocess(file){const bitmap=await createImageBitmap(file),max=1800,scale=Math.min(2,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();const img=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<img.data.length;i+=4){const y=.299*img.data[i]+.587*img.data[i+1]+.114*img.data[i+2],v=y>175?255:y<85?0:y;img.data[i]=img.data[i+1]=img.data[i+2]=v}ctx.putImageData(img,0,0);return canvas}
async function ensureTesseract(){if(window.Tesseract)return window.Tesseract;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js';s.onload=resolve;s.onerror=()=>reject(new Error('OCR 모듈을 불러오지 못했습니다.'));document.head.appendChild(s)});return window.Tesseract}
async function nativeDetect(file){if(!('TextDetector'in window))return '';try{const bitmap=await createImageBitmap(file),items=await new TextDetector().detect(bitmap);bitmap.close?.();return items.sort((a,b)=>(a.boundingBox?.y||0)-(b.boundingBox?.y||0)).map(x=>x.rawValue||'').join('\n')}catch{return ''}}
function setProgress(p,label,msg,error=false){const box=document.getElementById('ocrProgress');if(!box)return;box.classList.add('open');box.classList.toggle('ocrError',error);box.querySelector('i').style.width=`${clamp(p,0,100)}%`;box.querySelector('[data-label]').textContent=label;box.querySelector('[data-pct]').textContent=error?'확인 필요':`${Math.round(p)}%`;box.querySelector('small').textContent=msg}
function classOptions(selected){return state.settings.assetClasses.map(c=>`<option value="${esc(c.id)}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>`).join('')}
function readRows(){return [...document.querySelectorAll('.ocrRow')].map((el,i)=>{const value=parseMoney(el.querySelector('[data-o=value]').value),profit=parseMoney(el.querySelector('[data-o=profit]').value);return {line:i+1,name:el.querySelector('[data-o=name]').value.trim(),qty:parseMoney(el.querySelector('[data-o=qty]').value),value,cost:value-profit,class:el.querySelector('[data-o=class]').value}})}
function updateSummary(){const current=readRows(),sum=current.reduce((s,r)=>s+r.value,0),cost=current.reduce((s,r)=>s+r.cost,0),total=parseMoney(document.getElementById('ocrTotal')?.value)||sum,cash=total-sum,invalid=current.filter(r=>!r.name||r.qty<0||r.value<0||r.cost<0);document.getElementById('ocrSummary').innerHTML=`<div class="ocrSummaryRow"><span>인식 종목</span><b>${current.length}개</b></div><div class="ocrSummaryRow"><span>평가금액 합계</span><b>${fmt(sum)}</b></div><div class="ocrSummaryRow"><span>계산 원금</span><b>${fmt(cost)}</b></div><div class="ocrSummaryRow"><span>현금 반영</span><b class="${cash<0?'bad':''}">${fmt(cash)}</b></div>`;const btn=document.getElementById('ocrApply');btn.disabled=!current.length||invalid.length||cash<0;btn.textContent=current.length?`검토한 ${current.length}개 종목 반영`:'인식 후 반영'}
function renderRows(next){rows=next;const host=document.getElementById('ocrRows');host.innerHTML=next.map((r,i)=>`<div class="ocrRow"><div class="ocrRowHead"><b>${i+1}번째 상품</b><span>인식 ${r.confidence||80}%</span></div><div class="field"><label>종목명</label><input data-o="name" value="${esc(r.name)}"></div><div class="ocrGrid"><div class="field"><label>수량</label><input data-o="qty" inputmode="numeric" value="${Number(r.qty).toLocaleString('ko-KR')}"></div><div class="field"><label>평가금액</label><input data-o="value" inputmode="numeric" value="${Number(r.value).toLocaleString('ko-KR')}"></div><div class="field"><label>평가손익</label><input data-o="profit" inputmode="numeric" value="${Number(r.profit??r.value-r.cost).toLocaleString('ko-KR')}"></div><div class="field"><label>자산군</label><select data-o="class">${classOptions(r.class||guessClass(r.name))}</select></div></div></div>`).join('');host.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',updateSummary));updateSummary()}
async function run(file){setProgress(5,'사진 준비','표를 선명하게 변환하고 있습니다.');try{let text=window.__PENSION_OCR_TEST_TEXT||await nativeDetect(file);if(!text){const T=await ensureTesseract(),img=await preprocess(file),worker=await T.createWorker('kor+eng',1,{logger:m=>{if(m.status==='recognizing text')setProgress(15+(m.progress||0)*70,'사진 읽는 중',`문자를 찾고 있습니다 · ${Math.round((m.progress||0)*100)}%`)},workerPath:'https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/worker.min.js',corePath:'https://cdn.jsdelivr.net/npm/tesseract.js-core@5.1.1',langPath:'https://tessdata.projectnaptha.com/4.0.0_fast'});try{const result=await worker.recognize(img);text=result.data.text||''}finally{await worker.terminate()}}let parsed=parseBrokerOcr(text);if(!parsed.length&&window.__PENSION_OCR_TEST_ROWS)parsed=clone(window.__PENSION_OCR_TEST_ROWS);if(!parsed.length)throw new Error('종목 행을 찾지 못했습니다. 표 전체가 보이는 캡처를 사용하세요.');renderRows(parsed);document.getElementById('ocrTotal').value=parsed.reduce((s,r)=>s+r.value,0).toLocaleString('ko-KR');updateSummary();setProgress(100,'인식 완료','숫자만 한 번 확인한 뒤 반영하세요.')}catch(e){setProgress(100,'사진을 읽지 못했습니다',e.message||'다시 시도하세요.',true)}}
function render(){const title=document.getElementById('formTitle'),body=document.getElementById('formBody');title.textContent='사진으로 자산 읽기';body.innerHTML=`<div class="ocrIntro"><i>✓</i><div><b>사진은 인식 중에만 사용합니다.</b><br>종목명·수량·금액만 확인 후 저장하고 원본은 폐기합니다.</div></div><div class="field"><label>반영할 계좌</label><select id="ocrAccount"><option value="pension">연금저축</option><option value="irp">IRP</option></select></div><input id="ocrFile" type="file" accept="image/*" hidden><button class="ocrUpload" id="ocrUpload"><strong>잔고 화면 사진 선택</strong><span>보유 종목 표가 모두 보이는 캡처</span></button><div class="ocrProgress" id="ocrProgress"><div class="ocrProgressTop"><b data-label>준비</b><span data-pct>0%</span></div><div class="ocrTrack"><i></i></div><small></small></div><div class="ocrRows" id="ocrRows"></div>${moneyInput('ocrTotal','계좌 총액 · 선택',0,'예수금이 있으면 전체 총액을 입력하세요.')}<div class="ocrSummary" id="ocrSummary"><div class="ocrSummaryRow"><span>인식 종목</span><b>0개</b></div></div><button class="btn primary full" id="ocrApply" disabled>인식 후 반영</button><details class="ocrManual"><summary>자동 인식이 안 될 때 텍스트 입력</summary><textarea id="ocrManualText" placeholder="종목명 | 수량 | 평가금액 | 원금 | 자산군"></textarea><button class="btn full" id="ocrManualParse">텍스트 확인</button></details>`;const input=document.getElementById('ocrFile');document.getElementById('ocrUpload').onclick=()=>input.click();input.onchange=async()=>{const file=input.files?.[0];if(!file)return;cleanup();fileRef=file;objectUrl=URL.createObjectURL(file);await run(file)};bindMoneyInput('ocrTotal');document.getElementById('ocrTotal').oninput=updateSummary;document.getElementById('ocrManualParse').onclick=()=>{const parsed=PensionForms.parseHoldingText(document.getElementById('ocrManualText').value).map(r=>({...r,profit:r.value-r.cost,confidence:100}));if(!parsed.length)return toast('붙여넣은 종목을 찾지 못했어요');renderRows(parsed);document.getElementById('ocrTotal').value=parsed.reduce((s,r)=>s+r.value,0).toLocaleString('ko-KR');updateSummary()};document.getElementById('ocrApply').onclick=()=>{const current=readRows();try{applySnapshot(document.getElementById('ocrAccount').value,current,parseMoney(document.getElementById('ocrTotal').value),{source:'snapshot-ocr'});closeSheet('formSheet');renderAll(true);toast('사진에서 확인한 자산을 반영했어요')}catch(e){toast(e.message)}}}
function cleanup(){if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null}fileRef=null}
window.PensionOCR={render,cleanup,parseText:parseBrokerOcr,privacyState:()=>({hasObjectUrl:!!objectUrl,hasFileReference:!!fileRef}),parserAudit(){const valid=parseBrokerOcr('ACE 글로벌반도체TOP4 Plus 100,000 12 25,000\n현금 420,000 35,000');return {ok:valid.length===1&&valid[0].qty===12&&valid[0].value===420000&&valid[0].cost===320000,valid}}};
})();
