/* 개인연금 V2.4 분석·설정·장기입력 */

/* ===== js/60-final-completion.js ===== */
(()=>{
'use strict';
const FINAL_VERSION='2.4.0';
const LABEL={all:'전체',pension:'연금저축',irp:'IRP'};
document.title='개인연금 V2.4';
state.meta=state.meta||{};state.meta.appVersion=FINAL_VERSION;
state.settings=state.settings||{};
if(!Number.isFinite(Number(state.settings.pensionTaxCreditLimit)))state.settings.pensionTaxCreditLimit=6000000;
state.ui=state.ui||{};state.ui.performanceView=state.ui.performanceView||'table';state.ui.futureView=state.ui.futureView||'table';

function finalFullSignature(s){
  try{return JSON.stringify({appId:s.appId,dataId:s.dataId,schemaVersion:s.schemaVersion,profile:s.profile,settings:s.settings,accounts:s.accounts,years:s.years,accountYears:s.accountYears,dividendsByAsset:s.dividendsByAsset,runtime:s.runtime,ledger:s.ledger,snapshots:s.snapshots,archives:s.archives,extensions:s.extensions,lastUpdated:s.lastUpdated})}catch(_){return ''}
}
let finalLastSignature=finalFullSignature(state);
const finalPreviousSave=save;
save=function(){
  const sig=finalFullSignature(state),changed=sig!==finalLastSignature;
  if(changed){
    state.meta=state.meta||{};state.meta.revision=(Number(state.meta.revision)||0)+1;state.meta.updatedAt=isoNow();state.meta.appVersion=FINAL_VERSION;
    lastSignature=dataSignature(state);
    finalLastSignature=sig;
  }
  finalPreviousSave();
};

function finalAccountContribution(){
  const row=ensureYear(CURRENT_YEAR),paid=Math.max(0,Number(row.contribution)||0),ac=row.accountContribution||{};
  let pension=Math.max(0,Number(ac.pension)||0),irp=Math.max(0,Number(ac.irp)||0),sum=pension+irp;
  if(Math.abs(sum-paid)>1){
    if(sum>0){const scale=paid/sum;pension=Math.round(pension*scale);irp=paid-pension}
    else{const mp=Math.max(0,Number(state.settings.monthly?.pension)||0),mi=Math.max(0,Number(state.settings.monthly?.irp)||0),m=mp+mi;pension=m?Math.round(paid*mp/m):paid;irp=paid-pension}
  }
  return {row,paid,pension,irp};
}
function finalAnnualStatus(){
  const {paid,pension,irp}=finalAccountContribution(),monthly=(Number(state.settings.monthly?.pension)||0)+(Number(state.settings.monthly?.irp)||0),annualPlan=monthly*12;
  const annualLimit=Math.max(0,Number(state.settings.annualContributionLimit)||18000000),combinedTaxLimit=Math.max(0,Number(state.settings.taxCreditLimit)||9000000),pensionTaxLimit=Math.min(combinedTaxLimit,Math.max(0,Number(state.settings.pensionTaxCreditLimit)||6000000));
  const pensionEligible=Math.min(pension,pensionTaxLimit),taxEligible=Math.min(combinedTaxLimit,pensionEligible+irp);
  const taxRemain=Math.max(0,combinedTaxLimit-taxEligible),taxNeedIrp=pensionEligible>=pensionTaxLimit&&taxRemain>0;return {paid,pension,irp,monthly,annualPlan,annualLimit,combinedTaxLimit,pensionTaxLimit,pensionEligible,taxEligible,planRemain:Math.max(0,annualPlan-paid),limitRemain:Math.max(0,annualLimit-paid),taxRemain,taxNeedIrp,planPct:annualPlan?clamp(paid/annualPlan*100,0,100):0};
}
function finalContributionStatus(){
  const status=currentContributionStatus(),keys=['pension','irp'].filter(k=>Number(state.settings.monthly?.[k])>0),chips=keys.map(k=>({key:k,name:LABEL[k],done:!!status[k],amount:Number(state.settings.monthly[k])||0}));
  const done=chips.filter(x=>x.done).length;return {chips,total:chips.reduce((s,x)=>s+x.amount,0),label:!chips.length?'납입 계획 없음':done===chips.length?'이번 달 완료':done?`${done}/${chips.length} 계좌 완료`:'아직 기록 전'};
}
function finalRows(scope='all'){
  const source=scope==='all'?state.years:(state.accountYears?.[scope]||{});
  return Object.keys(source||{}).map(Number).sort((a,b)=>a-b).map(year=>({year,...source[year]}));
}
function finalScope(active,includeAll=true,attr='final-scope'){
  const keys=includeAll?['all','pension','irp']:['pension','irp'];
  return `<div class="scopeSegment">${keys.map(k=>`<button data-${attr}="${k}" class="${active===k?'active':''}">${LABEL[k]}</button>`).join('')}</div>`;
}
function bindFinalScope(attr,callback){document.querySelectorAll(`[data-${attr}]`).forEach(b=>b.onclick=()=>callback(b.dataset[attr.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]))}
function keyIndices(data,keyAges=[]){
  if(!data.length)return [];
  const idx=new Set([0,data.length-1]);
  if(data.length>2)idx.add(Math.round((data.length-1)/2));
  for(const age of keyAges){const i=data.findIndex(d=>d.age===age);if(i>=0)idx.add(i)}
  return [...idx].sort((a,b)=>a-b);
}

renderHome=function(){
  const total=totalAsset(),principal=totalPrincipal(),profit=total-principal,ret=principal?profit/principal*100:0,goal=goalStatus(),annual=finalAnnualStatus(),status=finalContributionStatus();
  const accountCards=Object.entries(state.accounts).map(([k,a])=>{const at=accountTotal(a),ap=at-a.principal,share=total?at/total*100:0;return `<button class="accountLink" data-account-link="${k}"><div><strong>${esc(a.name)}</strong><small class="tiny">전체의 ${share.toFixed(1)}%</small></div><span class="go">›</span><div class="accountStats"><div><span>원금</span><b>${man(a.principal)}</b></div><div><span>손익</span><b class="${ap>=0?'good':'bad'}">${ap>=0?'+':''}${man(ap)}</b></div><div><span>수익률</span><b class="${accountReturn(a)>=0?'good':'bad'}">${pct(accountReturn(a))}</b></div></div></button>`}).join('');
  const gapText=goal.gap>0?`목표 ${man(goal.goal)}까지 <b>${man(goal.gap)} 부족</b>`:`목표 ${man(goal.goal)} 달성 범위`;
  document.getElementById('home').innerHTML=`<div class="stack homeCompact">
    <section class="card hero pressable" id="totalCard"><div class="heroTop"><div class="eyebrow">개인연금 총자산</div><div style="display:flex;align-items:center;gap:8px"><span class="v1Badge">V2.4</span><span class="chevron ${state.ui.homeExpanded?'open':''}" id="totalChevron">⌄</span></div></div><div class="money">${fmt(total)}</div><div class="${profit>=0?'good':'bad'}" style="font-weight:900">누적 운용증가 ${profit>=0?'+':''}${fmt(profit)} · ${pct(ret)}</div><div class="metricGrid"><div class="metric"><small>누적 순납입</small><b>${fmt(principal)}</b></div><div class="metric accent"><small>마지막 갱신</small><b>${esc(state.lastUpdated)}</b></div></div><div class="expand ${state.ui.homeExpanded?'open':''}" id="accountExpand"><div>${accountCards}</div></div></section>
    <section class="card homeContributionUnified"><button class="homeContributionMain" id="homeContribution"><div class="homeContributionHead"><div><div class="eyebrow">${CURRENT_YEAR}년 납입</div><strong>${fmt(annual.paid)}</strong></div><div class="plan">올해 계획<br><b>${fmt(annual.annualPlan)}</b></div></div><div class="progress"><i style="width:${annual.planPct}%"></i></div><div class="statusChips">${status.chips.length?status.chips.map(x=>`<span class="statusChip ${x.done?'done':'wait'}">${esc(x.name)} ${x.done?'완료':'대기'}</span>`).join(''):'<span class="statusChip">납입 계획 없음</span>'}</div><div class="contributionSummary"><div><small>이번 달</small><b>${fmt(status.total)} · ${status.label}</b></div><div><small>계획까지</small><b>${fmt(annual.planRemain)} 남음</b></div><div><small>세액공제 대상</small><b>${fmt(annual.taxEligible)} / ${fmt(annual.combinedTaxLimit)}</b></div></div></button><details class="contributionDetails"><summary>한도와 계좌별 납입 자세히</summary><div class="contributionDetailGrid"><div><small>연금저축 납입</small><b>${fmt(annual.pension)}</b></div><div><small>IRP 납입</small><b>${fmt(annual.irp)}</b></div><div><small>연금저축 공제한도</small><b>${fmt(annual.pensionEligible)} / ${fmt(annual.pensionTaxLimit)}</b></div><div><small>연금계좌 총 납입한도</small><b>${fmt(annual.paid)} / ${fmt(annual.annualLimit)}</b></div></div><div class="goalFine">총 납입한도까지 ${fmt(annual.limitRemain)} 추가 가능 · 세액공제 한도까지 ${fmt(annual.taxRemain)} 남음${annual.taxNeedIrp?' · 남은 공제 한도는 IRP 납입 필요':''}</div></details></section>
    <button class="homeAction goalClear" id="homeGoal"><div class="goalClearTop"><div><div class="goalClearLead">현재 계획대로라면 ${state.profile.retirementAge}세부터</div><div class="goalClearMoney"><em>월 ${man(goal.real)}</em> 예상</div></div><span class="goalProgressPill">목표의 ${Math.round(goal.p)}%</span></div><div class="goalGap">${gapText}</div><div class="goalFine">${state.profile.retirementAge}세 당시 세전 첫 월인출 예상 ${man(goal.nominal)} · 예상자산 연 4% 인출 기준 · 물가 ${state.settings.inflation}%로 현재가치 환산</div></button>
  </div>`;
  document.getElementById('totalCard').addEventListener('click',e=>{if(e.target.closest('[data-account-link]'))return;state.ui.homeExpanded=!state.ui.homeExpanded;document.getElementById('accountExpand').classList.toggle('open',state.ui.homeExpanded);document.getElementById('totalChevron').classList.toggle('open',state.ui.homeExpanded);save()});
  document.querySelectorAll('[data-account-link]').forEach(b=>b.onclick=e=>{e.stopPropagation();navigate('account',b.dataset.accountLink)});
  document.getElementById('homeContribution').onclick=()=>quickForm('contribution');document.getElementById('homeGoal').onclick=()=>navigate('future');
};

renderPerformance=function(el){
  const scope=['all','pension','irp'].includes(state.ui.analysisScope)?state.ui.analysisScope:'all',data=finalRows(scope),view=state.ui.performanceView==='graph'?'graph':'table';
  if(!data.length){el.innerHTML=finalScope(scope)+`<div class="card empty"><b>이 계좌의 실제 성과 기록이 없어요</b><p>과거 연도 요약을 입력하면 표와 그래프가 생성됩니다.</p></div>`;bindFinalScope('final-scope',v=>{state.ui.analysisScope=v;renderPerformance(el);save()});return}
  state.ui.performanceIndex=clamp(Number(state.ui.performanceIndex)||data.length-1,0,data.length-1);
  const xIdx=keyIndices(data),chart=buildChart(data,{yValue:d=>Number(d.end)||0,cValue:d=>Number(d.cumulative)||0,xLabels:xIdx.map(i=>[i,String(data[i].year)]),idPrefix:'perf'});
  const latest=data.at(-1),profit=(Number(latest.end)||0)-(Number(latest.cumulative)||0),estimated=scope!=='all'&&state.meta?.accountHistoryEstimated?.[scope];
  el.innerHTML=`${finalScope(scope)}<div class="viewToolbar"><div class="viewToolbarTitle"><b>${LABEL[scope]} 실제 성과</b><br>기록된 총자산과 누적 순납입을 비교합니다.</div><div class="viewToggle"><button data-perf-view="table" class="${view==='table'?'active':''}">표</button><button data-perf-view="graph" class="${view==='graph'?'active':''}">그래프</button></div></div><div class="stack"><div class="card dataTableCard"><table class="table"><thead><tr><th>연도</th><th>실제 총자산</th><th>실제 순납입</th><th>운용증가</th></tr></thead><tbody>${data.slice().reverse().map(d=>{const p=(Number(d.end)||0)-(Number(d.cumulative)||0);return `<tr><td><strong>${d.year}</strong></td><td><strong>${man(d.end)}</strong><small class="${Number(d.return)>=0?'good':'bad'}">${pct(d.return)}</small></td><td>${man(d.cumulative)}</td><td class="${p>=0?'good':'bad'}">${p>=0?'+':''}${man(p)}</td></tr>`}).join('')}</tbody></table></div><div class="card chartCard finalChartCard ${view==='graph'?'open':''}"><div class="chartHead"><div><div class="chartTitle">실제 총자산과 실제 누적 순납입</div><div class="chartSub">세로축은 0원부터 표시해 과장을 줄였습니다</div></div><div class="legend"><span><i class="a"></i>실제 총자산</span><span><i class="b"></i>실제 순납입</span></div></div><div class="chart"><div class="chartTooltip" id="perfTooltip"></div>${chart.svg}</div><div class="detailBars"><div class="detailBar"><div class="detailBarTop"><span>실제 총자산</span><b id="perfTotal"></b></div><div class="barTrack"><div class="barFill" id="perfTotalBar"></div></div></div><div class="detailBar"><div class="detailBarTop"><span>실제 누적 순납입</span><b id="perfContrib"></b></div><div class="barTrack"><div class="barFill gray" id="perfContribBar"></div></div></div><div class="detailBar"><div class="detailBarTop"><span>운용증가</span><b id="perfProfit"></b></div><div class="barTrack"><div class="barFill green" id="perfProfitBar"></div></div></div></div></div><div class="dataBasisNote">최근 기록: 총자산 ${fmt(latest.end)} · 순납입 ${fmt(latest.cumulative)} · 운용증가 ${profit>=0?'+':''}${fmt(profit)}${estimated?' · 계좌별 과거값 일부는 추정치이므로 실제 기록 입력 권장':''}</div></div>`;
  const update=(i,commit)=>{const d=data[i],p=(Number(d.end)||0)-(Number(d.cumulative)||0),max=Math.max(Number(d.end)||0,1),point=chart.pts[i],tip=document.getElementById('perfTooltip');state.ui.performanceIndex=i;updateChartSelection('perf',chart,i);if(tip){tip.style.left=`${clamp(point.x/chart.W*100,18,82)}%`;tip.innerHTML=`${d.year}년<br>${man(d.end)} · ${pct(d.return)}`};document.getElementById('perfTotal').textContent=fmt(d.end);document.getElementById('perfContrib').textContent=fmt(d.cumulative);document.getElementById('perfProfit').textContent=`${p>=0?'+':''}${fmt(p)}`;document.getElementById('perfTotalBar').style.width='100%';document.getElementById('perfContribBar').style.width=`${clamp((Number(d.cumulative)||0)/max*100,0,100)}%`;document.getElementById('perfProfitBar').style.width=`${clamp(Math.abs(p)/max*100,0,100)}%`;if(commit)save()};
  update(state.ui.performanceIndex,false);bindChart('perfHit',data,chart,update);
  document.querySelectorAll('[data-perf-view]').forEach(b=>b.onclick=()=>{state.ui.performanceView=b.dataset.perfView;renderPerformance(el);save()});bindFinalScope('final-scope',v=>{state.ui.analysisScope=v;state.ui.performanceIndex=999;renderPerformance(el);save()});
};

renderAccum=function(el){
  const data=projection(),view=state.ui.futureView==='graph'?'graph':'table',goal=goalStatus(),ages=[state.profile.age,40,50,60,state.profile.retirementAge].filter((v,i,a)=>v>=state.profile.age&&v<=state.profile.retirementAge&&a.indexOf(v)===i),milestones=ages.map(age=>data.find(d=>d.age===age)).filter(Boolean),xIdx=keyIndices(data,ages),chart=buildChart(data,{yValue:d=>Number(d.end)||0,cValue:d=>Number(d.cumulative)||0,xLabels:xIdx.map(i=>[i,`${data[i].age}세`]),idPrefix:'future'});
  let selectedIndex=data.findIndex(d=>d.age===state.ui.futureAge);if(selectedIndex<0)selectedIndex=data.length-1;
  el.innerHTML=`<div class="viewToolbar"><div class="viewToolbarTitle"><b>미래 예상 경로</b><br>예상 총자산과 예상 누적 순납입을 구분합니다.</div><div class="viewToggle"><button data-future-view="table" class="${view==='table'?'active':''}">표</button><button data-future-view="graph" class="${view==='graph'?'active':''}">그래프</button></div></div><div class="stack"><div class="card dataTableCard"><table class="table"><thead><tr><th>나이</th><th>예상 총자산</th><th>예상 순납입</th><th>예상 운용증가</th></tr></thead><tbody>${milestones.map(d=>`<tr><td class="futureMilestone">${d.age}세</td><td>${man(d.end)}</td><td>${man(d.cumulative)}</td><td class="${d.operating>=0?'good':'bad'}">${d.operating>=0?'+':''}${man(d.operating)}</td></tr>`).join('')}</tbody></table></div><div class="card chartCard finalChartCard ${view==='graph'?'open':''}"><div class="chartHead"><div><div class="chartTitle">예상 총자산과 예상 누적 순납입</div><div class="chartSub">기대수익률에 따른 시뮬레이션이며 확정값이 아닙니다</div></div><div class="legend"><span><i class="a"></i>예상 총자산</span><span><i class="b"></i>예상 순납입</span></div></div><div class="chart"><div class="chartTooltip" id="futureTooltip"></div>${chart.svg}</div><div class="detailBars"><div class="detailBar"><div class="detailBarTop"><span>예상 총자산</span><b id="futureTotal"></b></div><div class="barTrack"><div class="barFill" id="futureTotalBar"></div></div></div><div class="detailBar"><div class="detailBarTop"><span>예상 누적 순납입</span><b id="futureContrib"></b></div><div class="barTrack"><div class="barFill gray" id="futureContribBar"></div></div></div><div class="detailBar"><div class="detailBarTop"><span>예상 운용증가</span><b id="futureProfit"></b></div><div class="barTrack"><div class="barFill green" id="futureProfitBar"></div></div></div></div></div><div class="card goalClear"><div class="goalClearTop"><div><div class="goalClearLead">${state.profile.retirementAge}세부터 현재 돈 가치 기준</div><div class="goalClearMoney"><em>월 ${man(goal.real)}</em> 예상</div></div><span class="goalProgressPill">목표의 ${Math.round(goal.p)}%</span></div><div class="goalGap">${goal.gap>0?`목표 월 ${man(goal.goal)}까지 <b>${man(goal.gap)} 부족</b>`:`목표 월 ${man(goal.goal)} 달성 범위`}</div><div class="goalFine">당시 세전 첫 월인출 예상 ${man(goal.nominal)} · 예상자산 연 4% 인출 기준 · 적립 수익률 ${state.settings.returnRate}% · 물가 ${state.settings.inflation}%</div></div><div class="dataBasisNote">미래 표와 그래프의 ‘순납입’은 지금까지의 누적 순납입에 앞으로의 월 납입 계획을 더한 예상값입니다.</div></div>`;
  const update=(i,commit)=>{const d=data[i],max=Math.max(Number(d.end)||0,1),point=chart.pts[i],tip=document.getElementById('futureTooltip');state.ui.futureAge=d.age;updateChartSelection('future',chart,i);if(tip){tip.style.left=`${clamp(point.x/chart.W*100,18,82)}%`;tip.innerHTML=`${d.age}세<br>${man(d.end)}`};document.getElementById('futureTotal').textContent=fmt(d.end);document.getElementById('futureContrib').textContent=fmt(d.cumulative);document.getElementById('futureProfit').textContent=`${d.operating>=0?'+':''}${fmt(d.operating)}`;document.getElementById('futureTotalBar').style.width='100%';document.getElementById('futureContribBar').style.width=`${clamp((Number(d.cumulative)||0)/max*100,0,100)}%`;document.getElementById('futureProfitBar').style.width=`${clamp(Math.abs(Number(d.operating)||0)/max*100,0,100)}%`;if(commit)save()};
  update(selectedIndex,false);bindChart('futureHit',data,chart,update);document.querySelectorAll('[data-future-view]').forEach(b=>b.onclick=()=>{state.ui.futureView=b.dataset.futureView;renderAccum(el);save()});
};

const finalPreviousSettings=renderSettings;
renderSettings=function(){
  finalPreviousSettings();const body=document.getElementById('settingsBody'),saveBar=body?.querySelector('.saveBar');if(!body||!saveBar)return;
  const taxSection=[...body.querySelectorAll('.settingsSection')].find(x=>x.querySelector('.settingsTitle')?.textContent==='연간 납입 한도');
  if(taxSection&&!document.getElementById('setPensionTaxLimit')){const f=document.createElement('div');f.className='field';f.innerHTML=`<label>연금저축 세액공제 한도</label><input id="setPensionTaxLimit" type="text" inputmode="numeric" value="${Number(state.settings.pensionTaxCreditLimit||6000000).toLocaleString('ko-KR')}"><div class="fieldHint">연금저축 단독 한도와 IRP 포함 합계를 분리 계산합니다.</div>`;taxSection.insertBefore(f,taxSection.querySelector('.field:nth-of-type(2)')||null);const input=f.querySelector('input');input.addEventListener('blur',()=>{const n=parseMoney(input.value);input.value=n?Number(n).toLocaleString('ko-KR'):''})}
  const btn=document.getElementById('saveSettings'),prior=btn.onclick;btn.onclick=()=>{const pensionLimit=parseMoney(document.getElementById('setPensionTaxLimit')?.value||0),combined=parseMoney(document.getElementById('setTaxLimit')?.value||0);if(pensionLimit>combined){document.getElementById('settingsError').textContent='연금저축 세액공제 한도는 통합 세액공제 한도보다 클 수 없어요.';return}settingsDraft.settings.pensionTaxCreditLimit=pensionLimit;prior()};
  const notice=body.querySelector('.sheetNotice');if(notice)notice.textContent=`저장 버튼을 눌러야 반영됩니다. 앱 ${FINAL_VERSION} · 데이터 구조 5`;
};

/* Final FAB: no wake-on-touch jitter. It appears on entry, hides after 10 seconds, and returns at the top or when the active Home/Account tab is tapped. */
const finalOldFab=document.getElementById('fab'),finalFab=finalOldFab.cloneNode(true);finalOldFab.replaceWith(finalFab);let finalFabTimer=null,finalLastY=window.scrollY;
function finalHideFab(){clearTimeout(finalFabTimer);finalFab.classList.remove('fabVisible')}
function finalShowFab(){if(!['home','account'].includes(state.ui.screen||'home')||document.querySelector('.overlay.open'))return finalHideFab();finalFab.classList.add('fabVisible');clearTimeout(finalFabTimer);finalFabTimer=setTimeout(finalHideFab,10000)}
finalFab.onclick=()=>{finalHideFab();openSheet('quickSheet')};
const finalPrevNavigate=navigate;navigate=function(screen,accountKey=null){finalPrevNavigate(screen,accountKey);requestAnimationFrame(()=>['home','account'].includes(screen)?finalShowFab():finalHideFab())};
window.addEventListener('scroll',()=>{const y=window.scrollY;if(y>finalLastY+8)finalHideFab();else if(y<40&&finalLastY-y>8)finalShowFab();finalLastY=y},{passive:true});
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>{const screen=b.dataset.screen;if(screen===state.ui.screen&&['home','account'].includes(screen))finalShowFab()}));
renderAll(true);finalLastSignature=finalFullSignature(state);save();finalShowFab();
})();


/* ===== js/70-audit-30y.js ===== */
(()=>{
'use strict';
const AUDIT_BUILD='2.4.0';
const AUDIT_LABEL={all:'전체',pension:'연금저축',irp:'IRP'};
function auditRows(scope='all'){const source=scope==='all'?state.years:(state.accountYears?.[scope]||{});return Object.keys(source||{}).map(Number).sort((a,b)=>a-b).map(year=>({year,...source[year]}))}
function auditScope(active,includeAll=true,attr='audit-scope'){const keys=includeAll?['all','pension','irp']:['pension','irp'];return `<div class="scopeSegment">${keys.map(k=>`<button data-${attr}="${k}" class="${active===k?'active':''}">${AUDIT_LABEL[k]}</button>`).join('')}</div>`}
function bindAuditScope(attr,callback){document.querySelectorAll(`[data-${attr}]`).forEach(b=>b.onclick=()=>{const key=attr.replace(/-([a-z])/g,(_,c)=>c.toUpperCase());callback(b.dataset[key])})}
function auditEnsureAccountYear(key,year=CURRENT_YEAR){state.accountYears=state.accountYears||{pension:{},irp:{}};state.accountYears[key]=state.accountYears[key]||{};if(!state.accountYears[key][year]){const current=year===CURRENT_YEAR,a=state.accounts[key];state.accountYears[key][year]={start:current?accountTotal(a):0,end:current?accountTotal(a):0,cumulative:current?(Number(a.principal)||0):0,contribution:0,operating:0,realized:0,return:0,dividend:0,reinvested:0,monthly:Array(12).fill(0)}}const r=state.accountYears[key][year];r.monthly=Array.isArray(r.monthly)?r.monthly.slice(0,12):Array(12).fill(0);while(r.monthly.length<12)r.monthly.push(0);return r}
function auditSyncCurrentAccountYears(){for(const key of ['pension','irp']){const r=auditEnsureAccountYear(key,CURRENT_YEAR),a=state.accounts[key];r.end=accountTotal(a);r.cumulative=Number(a.principal)||0;r.operating=r.end-(Number(r.start)||0)-(Number(r.contribution)||0);const base=(Number(r.start)||0)+(Number(r.contribution)||0)/2;r.return=base?r.operating/base*100:0}}
state.meta=state.meta||{};state.meta.appVersion=AUDIT_BUILD;state.ui=state.ui||{};

/* Central forecast: the setting is now the actual annual compound assumption, not an arbitrary return sequence. */
projection=function(){
  const monthly=Math.max(0,Number(state.settings.monthly?.pension)||0)+Math.max(0,Number(state.settings.monthly?.irp)||0),years=Math.max(1,Number(state.profile.retirementAge)-Number(state.profile.age)),annual=Number(state.settings.returnRate)||0,rm=Math.pow(1+annual/100,1/12)-1;
  let bal=totalAsset(),cum=totalPrincipal();const rows=[{age:state.profile.age,end:bal,cumulative:cum,operating:bal-cum,annual:0,start:bal}];
  for(let i=0;i<years;i++){const start=bal;for(let m=0;m<12;m++){bal*=1+rm;bal+=monthly}cum+=monthly*12;rows.push({age:Number(state.profile.age)+i+1,end:bal,cumulative:cum,operating:bal-cum,annual,start})}
  return rows;
};
projectNoContribution=function(){const years=Math.max(0,Number(state.profile.retirementAge)-Number(state.profile.age)),rate=Number(state.settings.returnRate)||0;return totalAsset()*Math.pow(1+rate/100,years)};
withdrawalSim=function(asset,key){
  const defs={dividend:{name:'보수적 인출',desc:'초기 3.5%로 시작해 잔액 보존을 우선',rate:.035,inflation:.01},balanced:{name:'균형 인출',desc:'초기 4%와 완만한 인상으로 균형',rate:.04,inflation:.015},fixed:{name:'적극 인출',desc:'초기 5%를 고정해 초반 수령액을 높임',rate:.05,inflation:0}};
  const d=defs[key]||defs.balanced,annual=Number(state.settings.withdrawReturn)||0;let bal=Math.max(0,Number(asset)||0),w=bal*d.rate,total=0,depleted=0;const rows=[];
  for(let i=0;i<Number(state.settings.withdrawYears||30);i++){const start=bal,available=start*(1+annual/100),paid=Math.min(w,available);bal=Math.max(0,available-paid);total+=paid;rows.push({age:Number(state.profile.retirementAge)+i+1,start,withdraw:paid,end:bal,return:annual});if(!bal&&!depleted)depleted=i+1;w*=1+d.inflation}
  return {...d,key,startMonthly:(Number(asset)||0)*d.rate/12,end:bal,total,depleted,rows};
};

function auditTicks(data){if(!data.length)return[];const count=Math.min(5,data.length),out=new Set();for(let i=0;i<count;i++)out.add(Math.round(i*(data.length-1)/Math.max(1,count-1)));return [...out].sort((a,b)=>a-b)}
function auditTableRows(data){return data.map(d=>{const p=(Number(d.end)||0)-(Number(d.cumulative)||0);return `<tr><td><strong>${d.year}</strong></td><td><strong>${man(d.end)}</strong><small class="${Number(d.return)>=0?'good':'bad'}">${pct(d.return)}</small></td><td>${man(d.cumulative)}</td><td class="${p>=0?'good':'bad'}">${p>=0?'+':''}${man(p)}</td></tr>`}).join('')}

renderPerformance=function(el){
  const scope=['all','pension','irp'].includes(state.ui.analysisScope)?state.ui.analysisScope:'all',data=auditRows(scope),view=state.ui.performanceView==='graph'?'graph':'table';
  if(!data.length){el.innerHTML=auditScope(scope)+`<div class="card empty"><b>이 계좌의 실제 성과 기록이 없어요</b><p>과거 연도 요약을 입력하면 표와 그래프가 생성됩니다.</p></div>`;bindAuditScope('final-scope',v=>{state.ui.analysisScope=v;state.ui.performanceSelectionConfirmed=false;renderPerformance(el);save()});return}
  if(!state.ui.performanceSelectionConfirmed||!Number.isFinite(Number(state.ui.performanceIndex)))state.ui.performanceIndex=data.length-1;state.ui.performanceIndex=clamp(Number(state.ui.performanceIndex),0,data.length-1);
  const latest=data.at(-1),profit=(Number(latest.end)||0)-(Number(latest.cumulative)||0),estimated=scope!=='all'&&state.meta?.accountHistoryEstimated?.[scope],recent=data.slice(-10).reverse(),older=data.slice(0,-10).reverse();
  let content='',afterRender=null;
  if(view==='table')content=`<div class="card dataTableCard auditHistoryCard"><table class="table"><thead><tr><th>연도</th><th>실제 총자산</th><th>실제 순납입</th><th>운용증가</th></tr></thead><tbody>${auditTableRows(recent)}</tbody></table>${older.length?`<details class="auditHistoryMore"><summary>이전 ${older.length}년 전체 펼치기</summary><table class="table"><tbody>${auditTableRows(older)}</tbody></table></details>`:''}</div>`;
  else{const ticks=auditTicks(data),chart=buildChart(data,{yValue:d=>Number(d.end)||0,cValue:d=>Number(d.cumulative)||0,xLabels:ticks.map(i=>[i,String(data[i].year)]),idPrefix:'perf'});content=`<div class="card chartCard"><div class="chartHead"><div><div class="chartTitle">실제 총자산과 실제 누적 순납입</div><div class="chartSub">세로축을 0원부터 표시해 과장을 줄였습니다</div></div><div class="legend"><span><i class="a"></i>실제 총자산</span><span><i class="b"></i>실제 순납입</span></div></div><div class="chart"><div class="chartTooltip" id="perfTooltip"></div>${chart.svg}</div><div class="detailBars"><div class="detailBar"><div class="detailBarTop"><span>실제 총자산</span><b id="perfTotal"></b></div><div class="barTrack"><div class="barFill" id="perfTotalBar"></div></div></div><div class="detailBar"><div class="detailBarTop"><span>실제 누적 순납입</span><b id="perfContrib"></b></div><div class="barTrack"><div class="barFill gray" id="perfContribBar"></div></div></div><div class="detailBar"><div class="detailBarTop"><span>운용증가</span><b id="perfProfit"></b></div><div class="barTrack"><div class="barFill green" id="perfProfitBar"></div></div></div></div></div>`;
    afterRender=()=>{const update=(i,commit)=>{const d=data[i],p=(Number(d.end)||0)-(Number(d.cumulative)||0),max=Math.max(Number(d.end)||0,1),point=chart.pts[i],tip=document.getElementById('perfTooltip');state.ui.performanceIndex=i;if(commit)state.ui.performanceSelectionConfirmed=true;updateChartSelection('perf',chart,i);if(tip){tip.style.left=`${clamp(point.x/chart.W*100,18,82)}%`;tip.innerHTML=`${d.year}년<br>${man(d.end)} · ${pct(d.return)}`};document.getElementById('perfTotal').textContent=fmt(d.end);document.getElementById('perfContrib').textContent=fmt(d.cumulative);document.getElementById('perfProfit').textContent=`${p>=0?'+':''}${fmt(p)}`;document.getElementById('perfTotalBar').style.width='100%';document.getElementById('perfContribBar').style.width=`${clamp((Number(d.cumulative)||0)/max*100,0,100)}%`;document.getElementById('perfProfitBar').style.width=`${clamp(Math.abs(p)/max*100,0,100)}%`;if(commit)save()};update(state.ui.performanceIndex,false);bindChart('perfHit',data,chart,update)};
  }
  el.innerHTML=`${auditScope(scope)}<div class="viewToolbar"><div class="viewToolbarTitle"><b>${AUDIT_LABEL[scope]} 실제 성과</b><br>${data.length}년 기록 · 표와 그래프 중 하나만 표시합니다.</div><div class="viewToggle"><button data-perf-view="table" class="${view==='table'?'active':''}">표</button><button data-perf-view="graph" class="${view==='graph'?'active':''}">그래프</button></div></div><div class="stack">${content}<div class="dataBasisNote">최근 기록: 총자산 ${fmt(latest.end)} · 순납입 ${fmt(latest.cumulative)} · 운용증가 ${profit>=0?'+':''}${fmt(profit)}${estimated?' · 계좌별 과거값 일부는 추정치이므로 실제 기록 입력 권장':''}<br>연 수익률은 연중 납입이 고르게 이뤄졌다고 가정한 단순 추정치입니다.</div></div>`;
  if(afterRender)afterRender();
  document.querySelectorAll('[data-perf-view]').forEach(b=>b.onclick=()=>{state.ui.performanceView=b.dataset.perfView;if(b.dataset.perfView==='graph'&&!state.ui.performanceSelectionConfirmed)state.ui.performanceIndex=data.length-1;renderPerformance(el);save()});bindAuditScope('final-scope',v=>{state.ui.analysisScope=v;state.ui.performanceSelectionConfirmed=false;renderPerformance(el);save()});
};

renderAccum=function(el){
  const data=projection(),view=state.ui.futureView==='graph'?'graph':'table',goal=goalStatus(),ages=[state.profile.age,40,50,60,state.profile.retirementAge].filter((v,i,a)=>v>=state.profile.age&&v<=state.profile.retirementAge&&a.indexOf(v)===i),milestones=ages.map(age=>data.find(d=>d.age===age)).filter(Boolean);let selectedIndex=data.findIndex(d=>d.age===state.ui.futureAge);if(selectedIndex<0)selectedIndex=data.length-1;
  let content='',afterRender=null;
  if(view==='table')content=`<div class="card dataTableCard"><table class="table"><thead><tr><th>나이</th><th>예상 총자산</th><th>예상 순납입</th><th>예상 운용증가</th></tr></thead><tbody>${milestones.map(d=>`<tr><td class="futureMilestone">${d.age}세</td><td>${man(d.end)}</td><td>${man(d.cumulative)}</td><td class="${d.operating>=0?'good':'bad'}">${d.operating>=0?'+':''}${man(d.operating)}</td></tr>`).join('')}</tbody></table></div>`;
  else{const ticks=auditTicks(data),chart=buildChart(data,{yValue:d=>Number(d.end)||0,cValue:d=>Number(d.cumulative)||0,xLabels:ticks.map(i=>[i,`${data[i].age}세`]),idPrefix:'future'});content=`<div class="card chartCard"><div class="chartHead"><div><div class="chartTitle">예상 총자산과 예상 누적 순납입</div><div class="chartSub">설정한 연 ${state.settings.returnRate}% 복리의 중앙 예상입니다</div></div><div class="legend"><span><i class="a"></i>예상 총자산</span><span><i class="b"></i>예상 순납입</span></div></div><div class="chart"><div class="chartTooltip" id="futureTooltip"></div>${chart.svg}</div><div class="detailBars"><div class="detailBar"><div class="detailBarTop"><span>예상 총자산</span><b id="futureTotal"></b></div><div class="barTrack"><div class="barFill" id="futureTotalBar"></div></div></div><div class="detailBar"><div class="detailBarTop"><span>예상 누적 순납입</span><b id="futureContrib"></b></div><div class="barTrack"><div class="barFill gray" id="futureContribBar"></div></div></div><div class="detailBar"><div class="detailBarTop"><span>예상 운용증가</span><b id="futureProfit"></b></div><div class="barTrack"><div class="barFill green" id="futureProfitBar"></div></div></div></div></div>`;
    afterRender=()=>{const update=(i,commit)=>{const d=data[i],max=Math.max(Number(d.end)||0,1),point=chart.pts[i],tip=document.getElementById('futureTooltip');state.ui.futureAge=d.age;updateChartSelection('future',chart,i);if(tip){tip.style.left=`${clamp(point.x/chart.W*100,18,82)}%`;tip.innerHTML=`${d.age}세<br>${man(d.end)}`};document.getElementById('futureTotal').textContent=fmt(d.end);document.getElementById('futureContrib').textContent=fmt(d.cumulative);document.getElementById('futureProfit').textContent=`${d.operating>=0?'+':''}${fmt(d.operating)}`;document.getElementById('futureTotalBar').style.width='100%';document.getElementById('futureContribBar').style.width=`${clamp((Number(d.cumulative)||0)/max*100,0,100)}%`;document.getElementById('futureProfitBar').style.width=`${clamp(Math.abs(Number(d.operating)||0)/max*100,0,100)}%`;if(commit)save()};update(selectedIndex,false);bindChart('futureHit',data,chart,update)};
  }
  el.innerHTML=`<div class="viewToolbar"><div class="viewToolbarTitle"><b>미래 예상 경로</b><br>표와 그래프 중 하나만 표시합니다.</div><div class="viewToggle"><button data-future-view="table" class="${view==='table'?'active':''}">표</button><button data-future-view="graph" class="${view==='graph'?'active':''}">그래프</button></div></div><div class="stack">${content}<div class="card goalClear"><div class="goalClearTop"><div><div class="goalClearLead">${state.profile.retirementAge}세부터 현재 돈 가치 기준</div><div class="goalClearMoney"><em>월 ${man(goal.real)}</em> 예상</div></div><span class="goalProgressPill">목표의 ${Math.round(goal.p)}%</span></div><div class="goalGap">${goal.gap>0?`목표 월 ${man(goal.goal)}까지 <b>${man(goal.gap)} 부족</b>`:`목표 월 ${man(goal.goal)} 달성 범위`}</div><div class="goalFine">당시 첫 월수령 예상 ${man(goal.nominal)} · 적립 수익률 ${state.settings.returnRate}% · 물가 ${state.settings.inflation}% · ${state.settings.withdrawYears}년 수령 가정</div></div><div class="auditModelNote">중앙 예상은 설정한 수익률이 매년 일정하게 복리로 쌓인다는 계산입니다. 실제 수익 순서·수수료·세금에 따라 결과는 달라집니다.</div></div>`;
  if(afterRender)afterRender();
  document.querySelectorAll('[data-future-view]').forEach(b=>b.onclick=()=>{state.ui.futureView=b.dataset.futureView;renderAccum(el);save()});
};

/* Missed-month entry never mutates today's balance unless the selected month is the current month. */
renderContributionForm=function(title,body){
  title.textContent='납입 기록';const defaultMonth=CURRENT_KEY;
  body.innerHTML=`<div class="sheetNotice">이번 달은 실제 납입액을 현재 원금·현금과 올해 총납입에 반영합니다. 지난달은 중복 집계를 막기 위해 완료 표시만 보완합니다.</div><div class="field"><label>기록 월</label><input id="contribMonth" type="month" max="${CURRENT_KEY}" value="${defaultMonth}"></div><div class="inputHelp" id="contribMonthHelp"></div><div id="contribChoices"></div><label class="settingsInfo" id="contribBalanceChoice" style="display:flex;gap:10px;align-items:flex-start;margin-top:10px"><input id="contribAddCash" type="checkbox" checked style="width:20px;height:20px;flex:0 0 auto"><span><b>납입금을 현재 잔고의 현금에도 추가</b><span class="tiny" style="display:block;margin-top:3px">이미 최신 자산현황에 포함했다면 체크를 끄세요.</span></span></label><div class="settingsInfo" id="contribYearSummary" style="margin-top:10px"></div><button class="btn primary full" id="applyContribution" style="margin-top:14px">선택 계좌 기록</button>`;
  const draw=()=>{const m=document.getElementById('contribMonth').value||defaultMonth,year=Number(m.slice(0,4)),future=m>CURRENT_KEY,exists=year===CURRENT_YEAR||!!state.years?.[year],s=state.runtime.contributions[m]||{pension:false,irp:false},yr=state.years?.[year]||{contribution:0},annual=(Number(state.settings.monthly.pension)||0)+(Number(state.settings.monthly.irp)||0),planned=['pension','irp'].filter(k=>Number(state.settings.monthly[k])>0),missing=planned.filter(k=>!s[k]),host=document.getElementById('contribChoices'),btn=document.getElementById('applyContribution');document.getElementById('contribMonthHelp').textContent=future?'미래 달은 미리 완료 처리할 수 없습니다.':m===defaultMonth?'이번 달 기록은 실제 납입으로 처리되어 현재 잔고와 올해 총납입이 함께 늘어납니다.':'지난달 기록은 완료 여부만 보완합니다. 금액 수정은 과거 연도 기록에서 하세요.';const balanceChoice=document.getElementById('contribBalanceChoice');if(balanceChoice)balanceChoice.style.display=m===CURRENT_KEY&&!future?'flex':'none';document.getElementById('contribYearSummary').innerHTML=`<b>${year}년 총납입 ${fmt(yr.contribution||0)}</b><div class="tiny" style="margin-top:4px">현재 계획 연 ${fmt(annual*12)} · 법정 한도와 실제 공제 인정액은 별도 확인</div>`;if(future){host.innerHTML='<div class="settingsInfo">미래 달은 기록할 수 없습니다.</div>';btn.disabled=true;return}if(!exists){host.innerHTML='<div class="settingsInfo">이 연도의 자산 기록이 없습니다. 먼저 과거 연도 기록을 입력하세요.</div>';btn.disabled=true;return}if(!planned.length){host.innerHTML='<div class="settingsInfo">월 납입 계획이 없습니다. 설정에서 납입액을 정하세요.</div>';btn.disabled=true;return}if(!missing.length){host.innerHTML='<div class="settingsInfo">선택한 달의 계획된 납입이 모두 기록됐습니다.</div>';btn.disabled=true;return}btn.disabled=false;host.innerHTML=missing.map(k=>`<label class="quickItem" style="margin-top:10px"><input type="checkbox" data-contrib="${k}" checked style="width:20px;height:20px"><span><b>${state.accounts[k].name}</b><small>${fmt(state.settings.monthly[k])}${m===CURRENT_KEY?' 실제 납입 반영':' 완료 표시만'}</small></span><span></span></label>`).join('')};
  document.getElementById('contribMonth').onchange=draw;draw();
  document.getElementById('applyContribution').onclick=()=>{const monthKey=document.getElementById('contribMonth').value||defaultMonth;if(monthKey>CURRENT_KEY)return toast('미래 달은 기록할 수 없어요');const keys=[...document.querySelectorAll('[data-contrib]:checked')].map(x=>x.dataset.contrib);if(!keys.length)return toast('기록할 계좌를 선택하세요');const year=Number(monthKey.slice(0,4));if(year!==CURRENT_YEAR&&!state.years?.[year])return toast('먼저 해당 연도의 과거 기록을 입력하세요');const current=monthKey===CURRENT_KEY,addCash=current&&document.getElementById('contribAddCash')?.checked!==false,row=year===CURRENT_YEAR?ensureYear(year):state.years[year],status=state.runtime.contributions[monthKey]||{pension:false,irp:false};if(!current){for(const k of keys)if(!status[k])status[k]=true;state.runtime.contributions[monthKey]=status;save();closeSheet('formSheet');renderAll();return toast(`${monthKey.replace('-','년 ')}월 완료 이력을 보완했어요`)}const additions=keys.filter(k=>!status[k]).reduce((sum,k)=>sum+(Number(state.settings.monthly[k])||0),0),limit=Math.max(0,Number(state.settings.annualContributionLimit)||18000000);if((Number(row.contribution)||0)+additions>limit)return toast(`연간 총 납입 한도 ${fmt(limit)}를 넘습니다`);for(const k of keys){if(status[k])continue;const amount=Number(state.settings.monthly[k])||0;if(!amount)continue;const ar=state.accountYears?.[k]?.[year]||auditEnsureAccountYear(k,year);state.accounts[k].principal+=amount;if(addCash)state.accounts[k].cash+=amount;row.contribution=(Number(row.contribution)||0)+amount;row.accountContribution=row.accountContribution||{pension:0,irp:0};row.accountContribution[k]=(Number(row.accountContribution[k])||0)+amount;row.cumulative=(Number(row.cumulative)||0)+amount;if(addCash)row.end=(Number(row.end)||0)+amount;row.operating=(Number(row.end)||0)-(Number(row.start)||0)-(Number(row.contribution)||0);const rb=(Number(row.start)||0)+(Number(row.contribution)||0)/2;row.return=rb?row.operating/rb*100:0;ar.contribution=(Number(ar.contribution)||0)+amount;ar.cumulative=(Number(ar.cumulative)||0)+amount;if(addCash)ar.end=(Number(ar.end)||0)+amount;ar.operating=(Number(ar.end)||0)-(Number(ar.start)||0)-(Number(ar.contribution)||0);const ab=(Number(ar.start)||0)+(Number(ar.contribution)||0)/2;ar.return=ab?ar.operating/ab*100:0;window.PensionV1Record?.ledger('contribution',{date:`${monthKey}-01T00:00:00`,accountId:`account-${k}`,amount,note:`${monthKey} ${state.accounts[k].name} 납입`,source:addCash?'current-month-cash':'current-month-already-in-balance'});status[k]=true}state.runtime.contributions[monthKey]=status;updateYearFromAssets();save();closeSheet('formSheet');renderAll();toast(addCash?`${monthKey.replace('-','년 ')}월 납입과 현금을 기록했어요`:`${monthKey.replace('-','년 ')}월 납입원금만 기록했어요`)};
};

const auditPreviousDetail=renderDetailForm;
renderDetailForm=function(title,body){auditPreviousDetail(title,body);const btn=document.getElementById('applyDetail'),old=btn?.onclick;if(!btn||!old)return;btn.onclick=()=>{const date=document.getElementById('detailDate').value,year=Number(date.slice(0,4));if(year!==CURRENT_YEAR&&!state.years?.[year])return toast('먼저 해당 연도의 과거 기록을 입력하세요');old()}};

function auditParseHistory(text){const rows=[],errors=[];String(text||'').split(/\n+/).forEach((raw,idx)=>{const line=raw.trim();if(!line)return;const p=line.split(/\s*[|\t]\s*/);if(p.length<3){errors.push(idx+1);return}const year=Number(String(p[0]).replace(/[^0-9]/g,'')),end=parseMoney(p[1]),cumulative=parseMoney(p[2]),dividend=parseMoney(p[3]||0);if(year<1900||year>2200||end<0||cumulative<0||dividend<0){errors.push(idx+1);return}rows.push({year,end,cumulative,dividend})});rows.sort((a,b)=>a.year-b.year);return {rows,errors}}
function auditRenderHistory(title,body){
  title.textContent='과거 연도 기록';let scope=state.ui.historyScope||'all';const rowsFor=s=>auditRows(s).slice(-30).map(r=>`${r.year} | ${Math.round(r.end).toLocaleString('ko-KR')} | ${Math.round(r.cumulative).toLocaleString('ko-KR')} | ${Math.round(r.dividend||0).toLocaleString('ko-KR')}`).join('\n');
  body.innerHTML=`<div class="sheetNotice">최대 30년을 한 번에 확인할 수 있습니다. 입력한 연도만 추가·수정하며 다른 연도는 유지합니다. 현재 연도 총자산·순납입은 최신 계좌 값으로 다시 계산됩니다.</div>${auditScope(scope,true,'audit-history-scope')}<div class="field"><label>연도 | 연말 총자산 | 누적 순납입 | 연간 배당</label><textarea id="auditHistoryText" rows="14"></textarea><div class="historyExample">한 줄에 한 해 · 세로줄(|) 또는 탭 · 누적 순납입은 이전 연도보다 작을 수 없음</div></div><div class="settingsInfo historyPreview" id="auditHistoryPreview"></div><button class="btn primary full" id="auditApplyHistory" style="margin-top:14px">확인한 연도 반영</button>`;
  const ta=document.getElementById('auditHistoryText'),preview=document.getElementById('auditHistoryPreview');
  const update=()=>{const d=auditParseHistory(ta.value),dup=d.rows.find((r,i,a)=>a.findIndex(x=>x.year===r.year)!==i),decrease=d.rows.find((r,i)=>i&&r.cumulative<d.rows[i-1].cumulative);preview.innerHTML=`<b>${AUDIT_LABEL[scope]} · ${d.rows.length}개 연도 인식</b><div class="previewList"><div class="previewItem"><span>범위</span><b>${d.rows.length?`${d.rows[0].year}~${d.rows.at(-1).year}`:'-'}</b></div><div class="previewItem"><span>마지막 총자산</span><b>${d.rows.length?fmt(d.rows.at(-1).end):'-'}</b></div>${d.errors.length?`<div class="previewItem"><span>확인할 줄</span><b class="bad">${d.errors.join(', ')}</b></div>`:''}${dup?`<div class="previewItem"><span>중복 연도</span><b class="bad">${dup.year}</b></div>`:''}${decrease?`<div class="previewItem"><span>누적 순납입 감소</span><b class="bad">${decrease.year}</b></div>`:''}</div>`};
  const load=s=>{scope=s;state.ui.historyScope=s;document.querySelectorAll('[data-audit-history-scope]').forEach(b=>b.classList.toggle('active',b.dataset.auditHistoryScope===s));ta.value=rowsFor(s);update()};document.querySelectorAll('[data-audit-history-scope]').forEach(b=>b.onclick=()=>load(b.dataset.auditHistoryScope));ta.oninput=update;load(scope);
  document.getElementById('auditApplyHistory').onclick=()=>{const d=auditParseHistory(ta.value);if(d.errors.length)return toast(`${d.errors[0]}번째 줄을 확인하세요`);if(!d.rows.length)return toast('과거 연도 자료를 입력하세요');if(new Set(d.rows.map(r=>r.year)).size!==d.rows.length)return toast('중복 연도를 정리하세요');for(let i=1;i<d.rows.length;i++)if(d.rows[i].cumulative<d.rows[i-1].cumulative)return toast(`${d.rows[i].year}년 누적 순납입을 확인하세요`);const target=scope==='all'?state.years:(state.accountYears?.[scope]||(state.accountYears[scope]={}));for(const r of d.rows){const priorYears=Object.keys(target).map(Number).filter(y=>y<r.year).sort((a,b)=>b-a),prev=priorYears.length?target[priorYears[0]]:null,prevEnd=Number(prev?.end)||0,prevCum=Number(prev?.cumulative)||0;if(r.cumulative<prevCum)return toast(`${r.year}년 누적 순납입이 이전 기록보다 작아요`);const contribution=Math.max(0,r.cumulative-prevCum),operating=r.end-prevEnd-contribution,base=prevEnd+contribution/2,old=target[r.year]||{};target[r.year]={...old,start:prevEnd,end:r.end,cumulative:r.cumulative,contribution,operating,realized:Number(old.realized)||0,return:base?operating/base*100:0,dividend:r.dividend,reinvested:Number(old.reinvested)||0,monthly:Array.isArray(old.monthly)?old.monthly.slice(0,12):Array(12).fill(0)}}if(scope==='all')updateYearFromAssets();else{state.meta.accountHistoryEstimated[scope]=false;auditSyncCurrentAccountYears()}save();closeSheet('formSheet');renderAll();toast(`${AUDIT_LABEL[scope]} ${d.rows.length}년 기록을 반영했어요`)};
}
const auditPreviousQuick=quickForm;quickForm=function(type){if(type==='history'){document.getElementById('quickSheet').classList.remove('open');auditRenderHistory(document.getElementById('formTitle'),document.getElementById('formBody'));openSheet('formSheet',true);return}auditPreviousQuick(type)};document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>quickForm(b.dataset.quick));

const auditPrevAccount=renderAccount;renderAccount=function(){auditPrevAccount();if(state.ui.accountView!=='irp')return;const status=document.querySelector('#account .status');if(status){status.textContent=status.textContent.replace(/^위험자산 /,'위험자산 참고 추정 ');const note=document.createElement('div');note.className='auditRiskNote';note.textContent='상품의 법정 위험자산 분류는 증권사 기준이 우선입니다. 자산군 이름만으로 확정하지 않습니다.';status.after(note)}};

const auditPrevSettings=renderSettings;renderSettings=function(){auditPrevSettings();const notice=document.querySelector('#settingsBody .sheetNotice');if(notice)notice.textContent=`저장 버튼을 눌러야 반영됩니다. 앱 ${AUDIT_BUILD} · 데이터 구조 5`};

renderAll(true);save();
})();


/* ===== js/71-settings-guard.js ===== */
(()=>{'use strict';const previousAuditSettings=renderSettings;renderSettings=function(){previousAuditSettings();const btn=document.getElementById('saveSettings'),prior=btn?.onclick;if(!btn||!prior)return;btn.onclick=()=>{const p=parseMoney(document.getElementById('setPension')?.value||0),i=parseMoney(document.getElementById('setIrp')?.value||0),limit=parseMoney(document.getElementById('setAnnualLimit')?.value||0);if((p+i)*12>limit){document.getElementById('settingsError').textContent='월 납입 계획의 연환산액이 연금계좌 총 납입 한도를 넘습니다.';return}prior()}}})();

