/* 개인연금 V2.9.1 UI·입력·설정 안정화 */
(()=>{
'use strict';
const V29_VERSION='2.9.1';
const V29_CLASSES=[
  {id:'growth',name:'성장',target:55,riskWeight:100,color:'#2f80ed',hint:'S&P500·나스닥·반도체·AI·일반 주식형'},
  {id:'dividend',name:'인컴',target:15,riskWeight:85,color:'#22a06b',hint:'배당·커버드콜·리츠·인컴형'},
  {id:'bond',name:'안정',target:22,riskWeight:10,color:'#7b8ba3',hint:'채권·국채·MMF·머니마켓·CMA·단기금리'},
  {id:'gold',name:'대체',target:8,riskWeight:45,color:'#d69e2e',hint:'금·원자재·기타 대체투자'},
  {id:'other',name:'기타',target:0,riskWeight:50,color:'#9b7ed8',hint:'자동 분류가 어려운 자산'}
];
const V29_CLASS_MAP={dividend:'dividend',bond:'bond',cash:'bond',gold:'gold',growth:'growth',income:'dividend',stable:'bond',alternative:'gold',other:'other'};
const V29_KNOWN=[
  'TIGER 미국S&P500','ACE 미국S&P500','KODEX 미국S&P500TR','RISE 미국나스닥100','TIGER 미국나스닥100','ACE 글로벌반도체TOP4 Plus',
  'KODEX 미국배당다우존스','TIGER 미국배당다우존스','ACE 미국배당다우존스','KODEX 미국배당커버드콜액티브',
  'KODEX 머니마켓액티브','TIGER CD금리투자KIS(합성)','ACE 미국채10년','TIGER 미국채10년선물','KOFR금리액티브(합성)',
  'ACE KRX금현물','TIGER 골드선물(H)'
];
const v29N=v=>Number(v)||0;
const v29CurrentAge=()=>{const y=Number(state.profile?.birthYear),nowY=new Date().getFullYear();return Number.isInteger(y)?nowY-y+1:v29N(state.profile?.age)||32};
const v29Norm=v=>String(v||'').toLowerCase().replace(/\s+/g,'').replace(/[()\[\]{}·ㆍ,._-]/g,'');
const v29MapClass=id=>V29_CLASS_MAP[id]||'other';
const v29Class=id=>V29_CLASSES.find(c=>c.id===id)||V29_CLASSES.at(-1);
const v29ClassOptions=(selected='')=>V29_CLASSES.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>`).join('');
function v29GuessClass(name){
  const key=v29Norm(name),saved=state.settings?.assetAliases?.[key];if(saved&&V29_CLASSES.some(c=>c.id===saved))return saved;
  const n=String(name||'').toLowerCase();
  if(/머니마켓|money\s*market|\bmmf\b|\bcma\b|\bko?fr\b|cd금리|단기금리|초단기|단기채|채권|국채|미국채|회사채|예금|\brp\b/.test(n))return 'bond';
  if(/배당|dividend|커버드콜|covered\s*call|인컴|income|리츠|reit|우선주|월배당|고배당/.test(n))return 'dividend';
  if(/금현물|골드|gold|원자재|commodity|은선물|silver|원유|oil/.test(n))return 'gold';
  if(/s&p|snp|나스닥|nasdaq|반도체|semiconductor|ai|인공지능|테크|tech|성장|growth|모멘텀|퀄리티|전력|인프라|글로벌|선진국|코스피|코스닥|주식/.test(n))return 'growth';
  return 'other';
}
function v29EnsureState(){
  state.settings=state.settings||{};state.settings.assetAliases=state.settings.assetAliases&&typeof state.settings.assetAliases==='object'?state.settings.assetAliases:{};
  state.settings.input={mergeDuplicates:true,rememberClass:true,...(state.settings.input||{})};
  const old=Array.isArray(state.settings.assetClasses)?state.settings.assetClasses:[],targets={growth:0,dividend:0,bond:0,gold:0,other:0};
  for(const c of old){targets[v29MapClass(c.id)]+=v29N(c.target)}
  if(Object.values(targets).reduce((a,b)=>a+b,0)<=0)for(const c of V29_CLASSES)targets[c.id]=c.target;
  const total=Object.values(targets).reduce((a,b)=>a+b,0);if(Math.abs(total-100)>.01){targets.bond+=100-total}
  state.settings.assetClasses=V29_CLASSES.map(c=>({...c,target:Number(targets[c.id].toFixed(2)),extensions:{standard:true}}));
  for(const key of ['pension','irp'])for(const h of state.accounts?.[key]?.holdings||[]){
    h.class=v29MapClass(h.class||v29GuessClass(h.name));
    if(!state.settings.assetAliases[v29Norm(h.name)])state.settings.assetAliases[v29Norm(h.name)]=h.class;
    if(key==='irp'&&typeof h.risk!=='boolean'){h.risk=v29Class(h.class).riskWeight>=70;h.riskSource='estimated'}
  }
  state.settings.theme=['auto','light','dark'].includes(state.settings.theme)?state.settings.theme:'auto';
  state.ui=state.ui||{};state.meta=state.meta||{};state.meta.appVersion=V29_VERSION;
}
function v29Allocation(key){
  const a=state.accounts[key],sums=Object.fromEntries(V29_CLASSES.map(c=>[c.id,0]));let holdings=0;
  for(const h of a.holdings||[]){const value=Math.max(0,v29N(h.value));if(value<=0)continue;sums[v29MapClass(h.class)]+=value;holdings++}
  if(v29N(a.cash)>0)sums.bond+=v29N(a.cash);
  const total=Object.values(sums).reduce((s,n)=>s+n,0),active=V29_CLASSES.map(c=>({...c,value:sums[c.id],pct:total?sums[c.id]/total*100:0})).filter(c=>c.value>0.5);
  let cursor=0;const stops=[];for(const row of active){const next=cursor+row.pct;stops.push(`${row.color} ${cursor.toFixed(2)}% ${next.toFixed(2)}%`);cursor=next}
  return {total,holdings,active,gradient:stops.length?`conic-gradient(${stops.join(',')})`:'conic-gradient(#dfe5ee 0 100%)'};
}
function v29RiskSummary(key){
  if(key!=='irp')return null;const a=state.accounts.irp,total=accountTotal(a),risk=(a.holdings||[]).filter(h=>h.risk!==false).reduce((s,h)=>s+v29N(h.value),0),safe=Math.max(0,total-risk);return {risk,safe,total,pct:total?risk/total*100:0};
}
function v29AllocationCard(key){
  const pack=v29Allocation(key),risk=v29RiskSummary(key),legend=pack.active.map(row=>`<button class="v29LegendRow" data-v29-class="${row.id}"><i style="--dot:${row.color}"></i><span><b>${esc(row.name)}</b><small>${esc(row.hint)}</small></span><strong>${row.pct.toFixed(1)}%<small>${man(row.value)}</small></strong></button>`).join('');
  const card=document.createElement('section');card.className='card v29AllocationCard';card.innerHTML=`<div class="v29CardHead"><div><div class="eyebrow">현재 보유 기준</div><h2>자산 구성</h2></div><button class="v29TextBtn" id="v29EditAllocation">분류 편집</button></div>${pack.active.length?`<div class="v29AllocationBody"><button class="v29Donut" id="v29Donut" style="--donut:${pack.gradient}" aria-label="자산 구성 자세히"><span><b>${pack.active.length}</b><small>개 자산군</small></span></button><div class="v29Legend">${legend}</div></div>`:`<div class="empty"><b>구성할 자산이 없어요</b><p>자산현황을 입력하면 보유 중인 자산군만 표시됩니다.</p></div>`}${risk?`<div class="v29RiskStrip"><span>IRP 위험자산 참고 추정</span><b>${risk.pct.toFixed(1)}%</b><small>안전자산 ${(100-risk.pct).toFixed(1)}% · 증권사 법정 분류가 우선</small></div>`:''}<div class="v29AllocationFoot">0원 자산군은 숨기고, MMF·머니마켓·CMA·대기자금은 ‘안정’으로 합칩니다.</div>`;
  card.querySelector('#v29EditAllocation').onclick=()=>v29OpenAllocationEditor(key);card.querySelector('#v29Donut')?.addEventListener('click',()=>v29OpenAllocationEditor(key));card.querySelectorAll('[data-v29-class]').forEach(b=>b.onclick=()=>v29OpenAllocationEditor(key,b.dataset.v29Class));return card;
}
function v29OpenAllocationEditor(key,focus=''){
  const a=state.accounts[key],title=document.getElementById('formTitle'),body=document.getElementById('formBody');title.textContent='자산 분류';
  body.innerHTML=`<div class="sheetNotice">종목 이름으로 자동 분류하고, 여기서 바꾼 선택은 다음 입력에도 기억합니다. 보유하지 않은 자산군은 계좌 화면에 나타나지 않습니다.</div>${(a.holdings||[]).length?`<div class="v29ClassEditor">${a.holdings.map((h,i)=>`<div class="v29ClassEditRow ${focus&&h.class===focus?'focus':''}"><span><b>${esc(h.name)}</b><small>${man(h.value)}</small></span><select data-v29-class-edit="${i}">${v29ClassOptions(v29MapClass(h.class))}</select>${key==='irp'?`<label class="v29RiskToggle"><input type="checkbox" data-v29-risk-edit="${i}" ${h.risk!==false?'checked':''}><span>위험자산</span></label>`:''}</div>`).join('')}</div>`:'<div class="empty"><b>분류할 종목이 없어요</b><p>먼저 자산현황을 입력하세요.</p></div>'}<button class="btn primary full" id="v29SaveClasses" ${a.holdings.length?'':'disabled'}>분류 저장</button>`;
  document.getElementById('v29SaveClasses').onclick=()=>{a.holdings.forEach((h,i)=>{const cls=document.querySelector(`[data-v29-class-edit="${i}"]`)?.value||h.class;h.class=cls;state.settings.assetAliases[v29Norm(h.name)]=cls;if(key==='irp'){h.risk=!!document.querySelector(`[data-v29-risk-edit="${i}"]`)?.checked;h.riskSource='user'}});save();closeSheet('formSheet');renderAll(true);toast('자산 분류를 저장했어요')};openSheet('formSheet',true);
}
function v29KnownNames(){return [...new Set([...V29_KNOWN,...['pension','irp'].flatMap(k=>(state.accounts[k].holdings||[]).map(h=>h.name))])].sort((a,b)=>a.localeCompare(b,'ko'))}
function v29OpenHoldingForm(prefKey=state.ui.accountView){
  const title=document.getElementById('formTitle'),body=document.getElementById('formBody');title.textContent='종목 추가·수정';
  body.innerHTML=`<div class="sheetNotice">종목명 중복을 자동으로 찾아 새 항목 대신 기존 항목을 갱신합니다. 계좌 전체를 한 번에 바꿀 때는 ‘자산현황 갱신’을 사용하세요.</div><div class="field"><label>계좌</label><select id="v29HoldingAccount"><option value="pension" ${prefKey==='pension'?'selected':''}>연금저축</option><option value="irp" ${prefKey==='irp'?'selected':''}>IRP</option></select></div><div class="field"><label>종목명</label><input id="v29HoldingName" list="v29HoldingNames" autocomplete="off" placeholder="예: KODEX 머니마켓액티브"><datalist id="v29HoldingNames">${v29KnownNames().map(n=>`<option value="${esc(n)}"></option>`).join('')}</datalist><div class="inputHelp" id="v29DuplicateHelp">이름을 입력하면 자산군을 자동 제안합니다.</div></div><div class="twoFields"><div class="field"><label>평가금액</label><input id="v29HoldingValue" inputmode="numeric" placeholder="예: 5,800,000"></div><div class="field"><label>매입금액</label><input id="v29HoldingCost" inputmode="numeric" placeholder="예: 4,900,000"></div></div><div class="twoFields"><div class="field"><label>수량</label><input id="v29HoldingQty" inputmode="decimal" placeholder="예: 66"></div><div class="field"><label>자산군</label><select id="v29HoldingClass">${v29ClassOptions('growth')}</select></div></div><label class="balanceCheck" id="v29CashAdjustWrap"><input type="checkbox" id="v29CashAdjust"><span>신규 종목 금액만큼 계좌 대기자금에서 차감</span></label><div class="field v29RiskField" id="v29RiskField"><label>IRP 위험자산 분류</label><select id="v29HoldingRisk"><option value="auto">자동 추정</option><option value="risk">위험자산</option><option value="safe">안전자산</option></select></div><div class="settingsInfo" id="v29HoldingPreview"></div><button class="btn primary full" id="v29SaveHolding">종목 저장</button>`;
  const ids=['v29HoldingValue','v29HoldingCost'];ids.forEach(id=>{const el=document.getElementById(id);el.onblur=()=>{const n=parseMoney(el.value);el.value=n?Number(n).toLocaleString('ko-KR'):''}});
  const account=document.getElementById('v29HoldingAccount'),name=document.getElementById('v29HoldingName'),cls=document.getElementById('v29HoldingClass'),riskField=document.getElementById('v29RiskField'),cashWrap=document.getElementById('v29CashAdjustWrap'),preview=document.getElementById('v29HoldingPreview'),help=document.getElementById('v29DuplicateHelp'),btn=document.getElementById('v29SaveHolding');
  let classTouched=false;cls.onchange=()=>{classTouched=true;update()};
  const findExisting=()=>state.accounts[account.value].holdings.findIndex(h=>v29Norm(h.name)===v29Norm(name.value)&&v29Norm(name.value));
  const update=()=>{const key=account.value,idx=findExisting(),suggest=v29GuessClass(name.value);if(!classTouched)cls.value=suggest;riskField.style.display=key==='irp'?'block':'none';cashWrap.style.display=idx<0&&v29N(state.accounts[key].cash)>0?'flex':'none';help.textContent=idx>=0?'같은 이름의 기존 종목을 찾았습니다. 저장하면 중복 생성 없이 갱신합니다.':`자동 분류: ${v29Class(cls.value).name}`;help.className=`inputHelp ${idx>=0?'good':''}`;btn.textContent=idx>=0?'기존 종목 갱신':'새 종목 추가';preview.innerHTML=`<b>${esc(v29Class(cls.value).name)} · ${idx>=0?'기존 종목 갱신':'신규 등록'}</b><div class="tiny" style="margin-top:5px">${esc(v29Class(cls.value).hint)}</div>`};
  account.onchange=()=>{classTouched=false;update()};name.oninput=update;document.getElementById('v29HoldingClass').onchange=()=>{classTouched=true;update()};update();
  btn.onclick=()=>{const key=account.value,a=state.accounts[key],nm=name.value.trim(),value=parseMoney(document.getElementById('v29HoldingValue').value),cost=parseMoney(document.getElementById('v29HoldingCost').value),qty=Number(String(document.getElementById('v29HoldingQty').value).replace(/,/g,''))||0,classId=cls.value,idx=findExisting();if(!nm)return toast('종목명을 입력하세요');if(value<0||cost<0||qty<0)return toast('금액과 수량은 0 이상으로 입력하세요');if(value===0&&cost===0)return toast('평가금액 또는 매입금액을 입력하세요');const previous=idx>=0?a.holdings[idx]:{},riskMode=document.getElementById('v29HoldingRisk').value,risk=key==='irp'?(riskMode==='auto'?(typeof previous.risk==='boolean'?previous.risk:v29Class(classId).riskWeight>=70):riskMode==='risk'):undefined;const next=prepareHolding(key,{...previous,name:nm,value,cost:cost||value,qty,class:classId,dividend:v29N(previous.dividend),realized:v29N(previous.realized),risk,riskSource:key==='irp'?(riskMode==='auto'?'estimated':'user'):undefined},previous);if(idx>=0)a.holdings[idx]=next;else{a.holdings.push(next);if(document.getElementById('v29CashAdjust').checked)a.cash=Math.max(0,v29N(a.cash)-value)}state.settings.assetAliases[v29Norm(nm)]=classId;state.ui.accountView=key;state.lastUpdated=localDisplayDate(new Date());updateYearFromAssets();save();closeSheet('formSheet');renderAll(true);toast(idx>=0?'기존 종목을 갱신했어요':'종목을 추가했어요')};openSheet('formSheet',true);
}
async function v29ExportJson(){try{await window.PensionV1Data?.persistNow?.({strict:true,syncCloud:false});const data=clone(state),validation=window.PensionV1Data?.validate?.(data);if(validation&&!validation.ok)throw new Error(validation.errors[0]);const blob=new Blob([JSON.stringify({appId:'asset-os-pension',appVersion:V29_VERSION,schemaVersion:data.schemaVersion,createdAt:new Date().toISOString(),data},null,2)],{type:'application/json'}),name=`pension_${localYmd(new Date())}.json`;if(typeof v1Download==='function')v1Download(blob,name);else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}toast('검증된 JSON 내보내기를 시작했어요')}catch(e){toast(`JSON 내보내기 중단: ${e?.message||e}`)}}
function v29CsvEscape(v){let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
async function v29ExportCsv(){try{await window.PensionV1Data?.persistNow?.({strict:true,syncCloud:false});const validation=window.PensionV1Data?.validate?.(clone(state));if(validation&&!validation.ok)throw new Error(validation.errors[0]);const rows=[['date','account','type','asset','amount','note'],...(state.ledger||[]).filter(r=>r.status!=='void').map(r=>[String(r.date||'').slice(0,10),r.accountKey||String(r.accountId||'').replace('account-',''),r.type,r.assetName||'',r.amount||0,r.note||''])],text='\ufeff'+rows.map(r=>r.map(v29CsvEscape).join(',')).join('\r\n'),blob=new Blob([text],{type:'text/csv;charset=utf-8'}),name=`pension-ledger_${localYmd(new Date())}.csv`;if(typeof v1Download==='function')v1Download(blob,name);else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click()}toast('검증된 CSV 내보내기를 시작했어요')}catch(e){toast(`CSV 내보내기 중단: ${e?.message||e}`)}}
function v29OpenFutureEditor(){
  const baseMonthly=v29N(state.settings.monthly.pension)+v29N(state.settings.monthly.irp),saved=state.ui.v29Custom||state.ui.v21Custom||{monthly:baseMonthly,rate:v29N(state.settings.returnRate),retAge:v29N(state.profile.retirementAge),inflation:v29N(state.settings.inflation),withdrawYears:v29N(state.settings.withdrawYears),withdrawReturn:v29N(state.settings.withdrawReturn)};
  document.getElementById('formTitle').textContent='내 가정 비교';document.getElementById('formBody').innerHTML=`<div class="sheetNotice">기본 계획은 바꾸지 않고 비교 화면에만 적용합니다.</div><div class="field"><label>월 납입액</label><input id="v29FutureMonthly" inputmode="numeric" value="${Number(saved.monthly).toLocaleString('ko-KR')}"></div><div class="twoFields"><div class="field"><label>기대수익률</label><input id="v29FutureRate" type="number" step="0.1" value="${saved.rate}"></div><div class="field"><label>연금 개시 나이</label><input id="v29FutureRet" type="number" value="${saved.retAge}"></div></div><div class="twoFields"><div class="field"><label>물가상승률</label><input id="v29FutureInflation" type="number" step="0.1" value="${saved.inflation??state.settings.inflation}"></div><div class="field"><label>수령 기간</label><input id="v29FutureYears" type="number" value="${saved.withdrawYears??state.settings.withdrawYears}"></div></div><div class="field"><label>수령 중 수익률</label><input id="v29FutureWithdraw" type="number" step="0.1" value="${saved.withdrawReturn??state.settings.withdrawReturn}"></div><button class="btn primary full" id="v29FutureApply">내 가정 적용</button><button class="btn full" id="v29FutureReset" style="margin-top:10px">비교 가정 초기화</button>`;const m=document.getElementById('v29FutureMonthly');m.onblur=()=>{const n=parseMoney(m.value);m.value=n?Number(n).toLocaleString('ko-KR'):''};document.getElementById('v29FutureApply').onclick=()=>{const custom={monthly:parseMoney(m.value),rate:Number(document.getElementById('v29FutureRate').value),retAge:Number(document.getElementById('v29FutureRet').value),inflation:Number(document.getElementById('v29FutureInflation').value),withdrawYears:Number(document.getElementById('v29FutureYears').value),withdrawReturn:Number(document.getElementById('v29FutureWithdraw').value)};if(custom.monthly<0||custom.rate<-20||custom.rate>20||custom.retAge<v29CurrentAge()||custom.retAge>90||custom.inflation<0||custom.inflation>10||custom.withdrawYears<5||custom.withdrawYears>50||custom.withdrawReturn<-10||custom.withdrawReturn>15)return toast('비교 가정 값을 확인하세요');state.ui.v29Custom=custom;state.ui.v21Custom={monthly:custom.monthly,rate:custom.rate,retAge:custom.retAge};state.ui.v21Scenario='custom';state.ui.futureAge=custom.retAge;save();closeSheet('formSheet');renderFutureContent()};document.getElementById('v29FutureReset').onclick=()=>{delete state.ui.v29Custom;delete state.ui.v21Custom;state.ui.v21Scenario='base';state.ui.futureAge=state.profile.retirementAge;save();closeSheet('formSheet');renderFutureContent()};openSheet('formSheet',true);
}
function v29Project(custom){
  const cfg=custom||{monthly:v29N(state.settings.monthly.pension)+v29N(state.settings.monthly.irp),rate:v29N(state.settings.returnRate),retAge:v29N(state.profile.retirementAge),inflation:v29N(state.settings.inflation),withdrawYears:v29N(state.settings.withdrawYears),withdrawReturn:v29N(state.settings.withdrawReturn)},years=Math.max(0,cfg.retAge-v29CurrentAge()),rm=Math.pow(Math.max(.01,1+cfg.rate/100),1/12)-1;let bal=totalAsset();for(let i=0;i<years*12;i++){bal*=1+rm;bal+=cfg.monthly}
  /* 예상자산은 은퇴 시점 명목금액이다. 월연금은 먼저 현재가치로 환산한 뒤,
     수령 중 실질수익률과 수령기간을 적용해 계산한다. 같은 숫자를 홈·미래·비교에 공통 사용한다. */
  const inflationFactor=Math.pow(Math.max(.01,1+cfg.inflation/100),years),todayAsset=bal/inflationFactor,annualReal=(1+cfg.withdrawReturn/100)/(1+cfg.inflation/100)-1,months=Math.max(1,cfg.withdrawYears*12),r=Math.pow(Math.max(.01,1+annualReal),1/12)-1,den=1-Math.pow(1+r,-months),monthly=Math.abs(r)>1e-10&&Math.abs(den)>1e-10?todayAsset*r/den:todayAsset/months;return {asset:bal,todayAsset,monthly,cfg};
}
function v29EnhanceFuture(){
  const segment=document.querySelector('#future .v21Scenario'),safe=segment?.querySelector('[data-scenario="safe"]');safe?.remove();if(segment)segment.classList.add('v29TwoScenario');const customBtn=segment?.querySelector('[data-scenario="custom"]');if(customBtn){const clone=customBtn.cloneNode(true);customBtn.replaceWith(clone);clone.onclick=()=>v29OpenFutureEditor()}
  const edit=document.getElementById('v21EditCustom');if(edit){const clone=edit.cloneNode(true);edit.replaceWith(clone);clone.onclick=v29OpenFutureEditor}
  const stack=document.querySelector('#future .stack'),summary=stack?.querySelector('.v21FutureSummary');if(!stack||!summary)return;const base=v29Project(),custom=state.ui.v29Custom?v29Project(state.ui.v29Custom):null,selected=state.ui.v21Scenario==='custom'&&custom?custom:base,goal=v29N(state.settings.goalMonthly),gap=selected.monthly-goal;
  const assetEl=summary.querySelector('.v21FutureTop strong'),monthlyEl=summary.querySelector('.v21FutureKpi span:first-child b'),gapEl=summary.querySelector('.v21FutureKpi span:nth-child(2) b'),gapLabel=summary.querySelector('.v21FutureKpi span:nth-child(2)'),fine=summary.querySelector(':scope > small');if(assetEl)assetEl.textContent=man(selected.asset);if(monthlyEl)monthlyEl.textContent=man(selected.monthly);if(gapLabel)gapLabel.childNodes[0].textContent=gap>=0?'목표보다 ':'목표까지 ';if(gapEl){gapEl.textContent=`${man(Math.abs(gap))}${gap>=0?' 여유':' 부족'}`;gapEl.className=gap>=0?'good':'bad'}if(fine)fine.textContent=`오늘 돈 가치 · ${selected.cfg.withdrawYears}년 수령 · 수령 중 ${selected.cfg.withdrawReturn}% 가정 · 국민연금·세금·수수료 제외`;
  const card=document.createElement('section');card.className='card v29ScenarioCompare';card.innerHTML=custom?`<div class="v29CardHead"><div><div class="eyebrow">기본 계획과 비교</div><h2>내 가정 차이</h2></div><button class="v29TextBtn" id="v29EditScenario">가정 편집</button></div><div class="v29CompareGrid"><div><small>예상자산</small><b>${man(custom.asset)}</b><span class="${custom.asset>=base.asset?'good':'bad'}">${custom.asset>=base.asset?'+':''}${man(custom.asset-base.asset)}</span></div><div><small>현재가치 월연금</small><b>${man(custom.monthly)}</b><span class="${custom.monthly>=base.monthly?'good':'bad'}">${custom.monthly>=base.monthly?'+':''}${man(custom.monthly-base.monthly)}</span></div></div><div class="v29AssumptionLine">월 ${man(custom.cfg.monthly)} · 수익률 ${custom.cfg.rate}% · ${custom.cfg.retAge}세 개시 · 물가 ${custom.cfg.inflation}% · ${custom.cfg.withdrawYears}년 수령</div>`:`<button class="v29ScenarioEmpty" id="v29CreateScenario"><span><b>내 가정과 비교하기</b><small>월 납입·수익률·개시 나이·물가·수령기간을 한 번에 바꿉니다.</small></span><span>›</span></button>`;summary.after(card);card.querySelector('#v29EditScenario,#v29CreateScenario')?.addEventListener('click',v29OpenFutureEditor);
}
function v29EnhanceHome(){
  const home=document.getElementById('home');if(!home)return;const hero=home.querySelector('.v21HomeHero,.hero');hero?.classList.add('v29HomeHero');const coach=home.querySelector('#homeCoach,.uxHomeCoach');if(coach){const status=coach.querySelector('.v12CoachState')?.textContent||'';if(/정상|특이사항 없음|관찰/.test(status))coach.classList.add('v29CoachCompact')}
  const exact=home.querySelector('.v21Exact,.heroFoot');if(exact)exact.title='원 단위 총액과 누적 순납입';const future=home.querySelector('#v21Future'),project=v29Project(),goal=v29N(state.settings.goalMonthly),value=future?.querySelector('strong'),small=future?.querySelector('small');if(value)value.textContent=man(project.monthly);if(small)small.textContent=project.monthly>=goal?'목표 달성권 · 자세히 ›':`목표보다 ${man(goal-project.monthly)} 부족 · 자세히 ›`;
}
function v29EnhanceSettings(){
  const body=document.getElementById('settingsBody');if(!body)return;const notice=body.querySelector('.sheetNotice'),theme=body.querySelector('.v21ThemeSection'),first=body.querySelector('.settingsSection');if(theme){theme.classList.add('v29ThemeTop');notice?.after(theme)}
  const classRows=document.getElementById('classRows'),add=document.getElementById('addClass');if(classRows){classRows.innerHTML=state.settings.assetClasses.map((c,i)=>`<div class="v29TargetRow"><input class="className" data-i="${i}" value="${esc(c.name)}" readonly aria-label="자산군 이름"><span><small>${esc(c.hint)}</small></span><input class="classTarget" data-i="${i}" type="number" min="0" max="100" step="1" value="${c.target}" aria-label="${esc(c.name)} 목표 비중"><b>%</b></div>`).join('');add?.remove();const sum=document.getElementById('targetSum'),refreshSum=()=>{const total=[...classRows.querySelectorAll('.classTarget')].reduce((n,x)=>n+(Number(x.value)||0),0);if(sum){sum.textContent=`합계 ${total.toFixed(total%1?1:0)}% · 기타는 자동 분류가 어려운 종목에만 사용`;sum.classList.toggle('bad',Math.abs(total-100)>.01)}};classRows.querySelectorAll('.classTarget').forEach(x=>x.addEventListener('input',refreshSum));refreshSum();classRows.closest('.settingsSection')?.classList.add('v29ClassSettings')}
  if(!body.querySelector('#v29ClassificationGuide')){const section=classRows?.closest('.settingsSection'),guide=document.createElement('details');guide.id='v29ClassificationGuide';guide.className='v29Guide';guide.innerHTML=`<summary>자동 분류 기준 보기</summary><div>${V29_CLASSES.map(c=>`<p><b>${c.name}</b><span>${c.hint}</span></p>`).join('')}<small>종목별로 직접 바꾼 분류는 다음 입력에도 기억합니다. IRP의 법정 위험자산 여부는 증권사 기준이 우선입니다.</small></div>`;section?.appendChild(guide)}
  const dataLaunch=body.querySelector('#openDataCenter')?.closest('.settingsSection');if(dataLaunch&&theme)dataLaunch.classList.add('v29DataSettings');
  const n=body.querySelector('.sheetNotice');if(n)n.innerHTML=`<b>개인연금 V2.9.1</b> · 저장 버튼을 눌러야 반영됩니다.<br>테마·계획·분류·백업을 이 화면에서 관리합니다.`;
}
function v29EnhanceDataCenter(){
  const body=document.getElementById('dataCenterBody');if(!body||body.querySelector('#v29ExportJson'))return;const actions=body.querySelector('.dataActions');if(!actions)return;const extra=document.createElement('div');extra.className='v29ExportActions';extra.innerHTML=`<button class="dataAction" id="v29ExportJson"><span><strong>JSON 단독 내보내기</strong><small>다른 앱이나 AI 복구용 표준 원본</small></span><span class="arrow">↓</span></button><button class="dataAction" id="v29ExportCsv"><span><strong>원장 CSV 내보내기</strong><small>납입·배당·매도 기록을 표로 저장</small></span><span class="arrow">↓</span></button>`;actions.after(extra);document.getElementById('v29ExportJson').onclick=v29ExportJson;document.getElementById('v29ExportCsv').onclick=v29ExportCsv;const notice=body.querySelector('.sheetNotice');if(notice)notice.innerHTML=`<b>V2.9.1 데이터 보관</b><br>기기 저장과 독립 ZIP·JSON·CSV를 제공합니다. Firebase 클라우드 원본 연결은 V3.0 단계에서 별도로 검증합니다.`;
}
function v29UpgradeQuickSheet(){
  const grid=document.querySelector('#quickSheet .quickGrid');if(!grid||grid.querySelector('[data-quick="holding"]'))return;const detail=grid.querySelector('[data-quick="detail"]'),btn=document.createElement('button');btn.className='quickItem';btn.dataset.quick='holding';btn.innerHTML='<span class="quickIcon">◎</span><span><b>종목 추가·수정</b><small>자동 분류·중복 갱신</small></span><span>›</span>';grid.insertBefore(btn,detail);btn.onclick=()=>quickForm('holding');
}
function v29PatchGlobals(){
  try{guessClassId=v29GuessClass}catch(_){}try{guessClassRelease=v29GuessClass}catch(_){}try{classOptions=v29ClassOptions}catch(_){}try{releaseClassOptions=v29ClassOptions}catch(_){}
  if(typeof V1_PROJECT_ASSETS!=='undefined'){for(const f of ['v29.css','v29.js'])if(!V1_PROJECT_ASSETS.includes(f))V1_PROJECT_ASSETS.push(f)}
}
v29EnsureState();v29PatchGlobals();
const v29PrevAccount=renderAccount;renderAccount=function(){v29EnsureState();v29PrevAccount();const stack=document.querySelector('#account .accountWrap .stack'),holdings=stack?.querySelector('.card.holdings');if(!stack||!holdings)return;stack.querySelector('.v29AllocationCard')?.remove();stack.insertBefore(v29AllocationCard(state.ui.accountView),holdings);const metric=stack.querySelectorAll('.miniMetric small')[2];if(metric)metric.textContent='대기자금';if(!holdings.querySelector('.v29HoldingHead')){const head=document.createElement('div');head.className='v29HoldingHead';head.innerHTML=`<div><div class="eyebrow">현재 등록</div><h2>보유상품 ${state.accounts[state.ui.accountView].holdings.length}개</h2></div><button id="v29AddHolding">종목 추가</button>`;holdings.prepend(head);head.querySelector('#v29AddHolding').onclick=()=>v29OpenHoldingForm(state.ui.accountView)}holdings.querySelectorAll('.holdingRow').forEach((row,i)=>{const h=state.accounts[state.ui.accountView].holdings[i],small=row.querySelector('.holdingBtn>div>small');if(h&&small)small.textContent=`${v29Class(h.class).name} · ${Number(h.qty||0).toLocaleString('ko-KR')}주`})};
const v29PrevHome=renderHome;renderHome=function(){v29EnsureState();v29PrevHome();v29EnhanceHome()};
const v29PrevSettings=renderSettings;renderSettings=function(){v29EnsureState();v29PrevSettings();v29EnhanceSettings()};
const v29PrevFutureContent=renderFutureContent;renderFutureContent=function(){v29EnsureState();let restore=null;if(state.ui.v21Scenario==='custom'&&state.ui.v29Custom){restore={inflation:state.settings.inflation,withdrawYears:state.settings.withdrawYears,withdrawReturn:state.settings.withdrawReturn};state.settings.inflation=state.ui.v29Custom.inflation;state.settings.withdrawYears=state.ui.v29Custom.withdrawYears;state.settings.withdrawReturn=state.ui.v29Custom.withdrawReturn;state.ui.v21Custom={monthly:state.ui.v29Custom.monthly,rate:state.ui.v29Custom.rate,retAge:state.ui.v29Custom.retAge}}v29PrevFutureContent();if(restore)Object.assign(state.settings,restore);v29EnhanceFuture()};
const v29PrevQuick=quickForm;quickForm=function(type){if(type==='holding'){document.getElementById('quickSheet')?.classList.remove('open');v29OpenHoldingForm();return}v29PrevQuick(type)};
const v29PrevDataRefresh=typeof v1RefreshDataCenter==='function'?v1RefreshDataCenter:null;if(v29PrevDataRefresh){v1RefreshDataCenter=function(){v29PrevDataRefresh();v29EnhanceDataCenter()}}
const v29PrevSave=save;save=function(){v29EnsureState();state.meta.appVersion=V29_VERSION;v29PrevSave()};
const v29PrevRenderAll=renderAll;renderAll=function(keep=false){v29EnsureState();v29PrevRenderAll(keep);v29EnhanceHome();document.title='개인연금 V2.9.1';v29UpgradeQuickSheet();const sub=document.getElementById('headerSub');if(sub)sub.textContent=`${v29CurrentAge()}세 · ${state.profile.retirementAge}세 연금 개시 계획`;state.meta.appVersion=V29_VERSION};
v29UpgradeQuickSheet();
const v29DataHost=document.getElementById('dataCenterBody');if(v29DataHost)new MutationObserver(()=>v29EnhanceDataCenter()).observe(v29DataHost,{childList:true,subtree:false});document.addEventListener('click',e=>{if(e.target.closest('#openDataCenter'))setTimeout(v29EnhanceDataCenter,260)});
document.title='개인연금 V2.9.1';renderAll(true);save();
window.PensionV29={version:V29_VERSION,classes:V29_CLASSES,classify:v29GuessClass,allocation:v29Allocation,openHolding:v29OpenHoldingForm,openAllocation:v29OpenAllocationEditor,project:v29Project,ensure:v29EnsureState};
})();
