/* 개인연금 V2.0 RC6 - 화면 */
'use strict';
function progressBar(value){return `<div class="r5Progress"><i style="width:${clamp(value,0,100)}%"></i></div>`}
function accountCards(){
  const total=totalAsset();return Object.entries(state.accounts).map(([key,a])=>{const value=accountTotal(a),profit=value-Number(a.principal||0);return `<button class="accountLink" data-account-link="${key}"><div><b>${ACCOUNT_LABEL[key]}</b><small>전체 자산의 ${total?(value/total*100).toFixed(1):'0.0'}%</small></div><strong>${man(value)}<small class="${profit>=0?'good':'bad'}">${profit>=0?'+':''}${man(profit)}</small></strong><span>›</span></button>`}).join('');
}
function renderHome(){
  const out=retirementOutlook(),diag=homeAction(),annual=annualContributionStatus(),total=totalAsset(),principal=totalPrincipal(),profit=total-principal;
  const goalText=out.gap>0?`목표까지 월 ${man(out.gap)} 부족`:`목표 달성 범위`;
  const sample=state.meta?.sampleData?`<section class="sampleBanner"><div><b>검토용 샘플 데이터</b><span>화면 확인용 금액입니다. 실제 판단에 사용하지 마세요.</span></div><button id="startMyData">내 데이터 시작</button></section>`:'';
  document.getElementById('home').innerHTML=`<div class="stack">${sample}
    <button class="card rc6RetirementHero" id="homeGoal"><div class="r5HeroTop"><span>입력한 개인연금 계좌만</span><span>${state.profile.retirementAge}세부터</span></div><div class="rc6HeroLabel">예상 개인연금 월수령</div><div class="r5Monthly"><span>약 월</span> <strong>${man(out.base.realMonthly)}</strong></div><div class="rc6Range">오늘 돈 가치 · 보수 ${man(out.conservative.realMonthly)} ~ 기준 ${man(out.base.realMonthly)}</div><div class="r5GoalLine"><span>${goalText}</span><b>${Math.round(out.progress)}%</b></div>${progressBar(out.progress)}<div class="r5HeroFoot">${state.settings.withdrawYears}년 인출 가정 · 보장액 아님 · 국민연금 제외 · 자세히 ›</div></button>
    <button class="card rc6Action ${diag.tone}" id="homeCoach"><div class="rc6ActionTop"><span>이번 달 가장 중요한 한 가지</span><b>${esc(diag.state)}</b></div><h2>${esc(diag.title)}</h2><p>${esc(diag.reason)}</p><div class="rc6ActionButton">${esc(diag.action)} <span>›</span></div></button>
    <button class="card contributionCard" id="homeContribution"><div class="row"><div><div class="eyebrow">${CURRENT_YEAR}년 납입</div><div class="money small">${man(annual.paid)}</div></div><b class="blue">${Math.round(annual.progress)}%</b></div>${progressBar(annual.progress)}<div class="tiny">연간 계획 ${man(annual.annualPlan)} · 세액공제 기준 ${man(annual.taxLimit)} (${state.settings.taxRuleYear}년 설정)</div></button>
    <section class="card rc6AssetCard"><button class="rc6AssetHead" id="assetToggle"><div><small>현재 개인연금 자산</small><b>${man(total)}</b><span class="${profit>=0?'good':'bad'}">투자손익 ${profit>=0?'+':''}${man(profit)}</span></div><div><small>마지막 갱신</small><b>${esc(state.lastUpdated)}</b><span>${state.ui.homeExpanded?'⌃':'⌄'}</span></div></button><div class="expand ${state.ui.homeExpanded?'open':''}">${accountCards()}<div class="exactAmount">정확한 금액 ${fmt(total)} · 누적 순납입 ${fmt(principal)}</div></div></section>
  </div>`;
  document.getElementById('startMyData')?.addEventListener('click',()=>confirmAction('샘플 데이터를 지우고 내 데이터로 시작할까요?','현재 샘플 기록은 모두 삭제됩니다.',()=>{clearSampleData();toast('내 데이터 입력을 시작합니다');openForm('snapshot')}));
  document.getElementById('homeGoal').onclick=()=>navigate('future');document.getElementById('homeCoach').onclick=()=>runDiagnosisAction(diag);document.getElementById('homeContribution').onclick=()=>openForm('contribution');
  document.getElementById('assetToggle').onclick=()=>{state.ui.homeExpanded=!state.ui.homeExpanded;saveState({quiet:true});renderHome()};
  document.querySelectorAll('[data-account-link]').forEach(b=>b.onclick=()=>navigate('account',b.dataset.accountLink));
}
function holdingRows(accountKey,a){
  if(!a.holdings.length)return `<div class="empty"><b>등록된 상품이 없어요</b><p>자산현황 갱신에서 사진이나 텍스트로 입력하세요.</p></div>`;
  return a.holdings.map((h,i)=>{const profit=Number(h.value)-Number(h.cost),ret=h.cost?profit/h.cost*100:0,cls=state.settings.assetClasses.find(c=>c.id===h.class)?.name||'미분류';return `<div class="holdingRow"><button class="holdingBtn" data-holding="${i}"><div><b>${esc(h.name)}</b><small>${esc(cls)} · ${Number(h.qty||0).toLocaleString('ko-KR')}주</small></div><strong>${man(h.value)}<small class="${profit>=0?'good':'bad'}">${profit>=0?'+':''}${man(profit)} · ${pct(ret)}</small></strong></button><div class="holdingDetail" id="holding-${i}"><div class="holdingDetailInner"><div class="holdingDetailGrid"><div>원금<b>${fmt(h.cost)}</b></div><div>평가손익<b class="${profit>=0?'good':'bad'}">${profit>=0?'+':''}${fmt(profit)}</b></div><div>누적 분배금<b>${fmt(h.dividend||0)}</b></div><div>확정손익<b>${fmt(h.realized||0)}</b></div></div></div></div></div>`}).join('');
}
function renderAccount(){
  const key=state.ui.accountView,a=state.accounts[key],total=accountTotal(a),profit=total-Number(a.principal||0),alloc=allocationRows(key).filter(r=>r.value>0||r.current>0),risk=irpRiskStatus(),records=recentRecords(key,6);
  document.getElementById('account').innerHTML=`<div class="segment two"><i class="segmentIndicator ${key==='irp'?'right':''}"></i><button data-account="pension" class="${key==='pension'?'active':''}">연금저축</button><button data-account="irp" class="${key==='irp'?'active':''}">IRP</button></div><div class="stack">
  <section class="card hero"><div class="eyebrow">${ACCOUNT_LABEL[key]} 현재 자산</div><div class="money small">${man(total)}</div><div class="${profit>=0?'good':'bad'}" style="font-weight:900">${profit>=0?'+':''}${man(profit)} · ${pct(accountReturn(a))}</div><div class="three"><div class="miniMetric"><small>납입원금</small><b>${man(a.principal)}</b></div><div class="miniMetric"><small>평가손익</small><b>${man(profit)}</b></div><div class="miniMetric"><small>현금</small><b>${man(a.cash)}</b></div></div>${key==='irp'&&total?`<div class="status ${risk.riskPct>70?'warn':''}">위험자산 참고 추정 ${risk.riskPct.toFixed(1)}% · 분류 미확인 ${risk.unknownPct.toFixed(1)}%</div><div class="auditRiskNote">법정 위험자산 분류와 주문 가능 여부는 증권사 기준이 우선입니다.</div>`:''}</section>
  <section class="card"><div class="sectionTitle">자산 구성</div>${alloc.map(r=>`<div class="allocationRow"><div class="allocationTop"><b>${esc(r.name)}</b><span>${r.current.toFixed(1)}%</span></div><div class="allocBar"><i style="width:${clamp(r.current,0,100)}%"></i></div></div>`).join('')||'<div class="tiny">자산을 입력하면 비중이 표시됩니다.</div>'}</section>
  <section class="card holdings"><div class="sectionTitle">보유 상품</div>${holdingRows(key,a)}</section>
  <details class="card rc6Records"><summary>최근 기록 ${records.length}건</summary><div>${records.map(r=>`<button class="rc6Record" data-record="${r.id}"><span>${r.type==='contribution'?'납입':r.type==='dividend'?'배당·분배금':r.type==='sell'?'매도 손익':'자산 갱신'}<small>${String(r.date).slice(0,10)} · ${esc(r.assetName||ACCOUNT_LABEL[r.accountKey]||'')}</small></span><b>${r.type==='sell'?`${Number(r.realized)>=0?'+':''}${man(r.realized)}`:man(r.amount||0)}</b></button>`).join('')||'<div class="tiny">직접 입력한 기록이 없습니다.</div>'}</div></details>
  </div>`;
  document.querySelectorAll('[data-account]').forEach(b=>b.onclick=()=>{state.ui.accountView=b.dataset.account;saveState({quiet:true});renderAccount()});
  document.querySelectorAll('[data-holding]').forEach(b=>b.onclick=()=>document.getElementById(`holding-${b.dataset.holding}`).classList.toggle('open'));
  document.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>openRecordEditor(b.dataset.record));
}
function scopeControl(scope){return `<label class="rc6Scope"><span>분석 계좌</span><select id="analysisScope"><option value="all" ${scope==='all'?'selected':''}>전체</option><option value="pension" ${scope==='pension'?'selected':''}>연금저축</option><option value="irp" ${scope==='irp'?'selected':''}>IRP</option></select></label>`}
function simpleLineChart(rows,valueKey='end'){
  if(!rows.length)return '<div class="empty"><b>기록이 없어요</b></div>';
  const chart=chartPath(rows.map(r=>r[valueKey]),320,170,18),points=chart.points.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="${i===chart.points.length-1?4:2}"/>`).join('');
  const labels=[0,Math.floor((rows.length-1)/2),rows.length-1].filter((v,i,a)=>a.indexOf(v)===i).map(i=>`<text x="${chart.points[i].x}" y="164" text-anchor="middle">${rows[i].year}</text>`).join('');
  return `<svg class="rc6Chart" viewBox="0 0 320 170" aria-label="연도별 자산 추이"><path class="grid" d="M18 30H302M18 90H302M18 145H302"/><path class="line" d="${chart.path}"/>${points}${labels}</svg>`;
}
function renderPerformancePanel(root){
  const scope=state.ui.analysisScope,rows=performanceSeries(scope),latest=rows.at(-1),current=scopeTotal(scope),principal=scopePrincipal(scope),profit=current-principal,visible=state.ui.performanceExpanded?rows:[...rows].slice(-4);
  root.innerHTML=`${scopeControl(scope)}${rows.length?`<section class="card rc6Performance"><div class="row"><div><small>${ACCOUNT_LABEL[scope]} 최근 자산</small><div class="money small">${man(current)}</div></div><b class="${latest?.return>=0?'good':'bad'}">${pct(latest?.return||0)}</b></div>${simpleLineChart(rows)}<div class="summaryGrid"><div class="summaryBox"><small>누적 순납입</small><b>${man(principal)}</b></div><div class="summaryBox"><small>누적 투자손익</small><b class="${profit>=0?'good':'bad'}">${profit>=0?'+':''}${man(profit)}</b></div></div><div class="analysisNote">연 수익률은 연중 납입 시점을 단순화한 추정치입니다.</div></section><section class="card rc6YearList">${visible.slice().reverse().map(r=>`<div class="rc6Year"><b>${r.year}</b><div><strong>${man(r.end)}</strong><small>납입 ${man(r.contribution)} · 투자손익 ${r.profit>=0?'+':''}${man(r.profit)}</small></div><span class="${r.return>=0?'good':'bad'}">${pct(r.return)}</span></div>`).join('')}${rows.length>4?`<button id="toggleYears" class="textBtn">${state.ui.performanceExpanded?'최근 4개 연도만':'이전 연도 펼쳐보기'}</button>`:''}</section>`:`<div class="card empty"><b>${ACCOUNT_LABEL[scope]} 성과 기록이 없어요</b><p>자산현황과 과거 연도 요약을 입력하면 표시됩니다.</p></div>`}`;
  bindScope();document.getElementById('toggleYears')?.addEventListener('click',()=>{state.ui.performanceExpanded=!state.ui.performanceExpanded;saveState({quiet:true});renderAnalysisContent()});
}
function renderCashflowPanel(root){
  const scope=state.ui.analysisScope,rows=cashflowSeries(scope),latest=rows.at(-1)||{dividend:0,realized:0},rank=holdingsDividendRank(scope),max=Math.max(1,...rows.map(r=>r.dividend));
  root.innerHTML=`${scopeControl(scope)}<div class="stack"><section class="card"><div class="sectionTitle">${ACCOUNT_LABEL[scope]} 현금흐름</div><div class="summaryGrid"><div class="summaryBox"><small>${CURRENT_YEAR} 배당·분배금</small><b>${man(latest.dividend)}</b></div><div class="summaryBox"><small>${CURRENT_YEAR} 매도 확정손익</small><b class="${latest.realized>=0?'good':'bad'}">${latest.realized>=0?'+':''}${man(latest.realized)}</b></div></div></section><section class="card"><div class="sectionTitle">연도별 배당·분배금</div><div class="uxFlowRows">${rows.slice(-8).reverse().map(r=>`<div><div class="uxFlowRowTop"><span>${r.year}</span><b>${man(r.dividend)}</b></div><div class="uxFlowRowTrack"><i style="width:${clamp(r.dividend/max*100,0,100)}%"></i></div></div>`).join('')||'<div class="tiny">기록이 없습니다.</div>'}</div></section>${rank.length?`<section class="card"><div class="sectionTitle">기여 상품</div>${rank.slice(0,5).map(([name,value])=>`<div class="r5Rank"><span>${esc(name)}</span><b>${man(value)}</b></div>`).join('')}</section>`:''}<div class="analysisNote">배당은 현금흐름이며 자산 성장 여부는 성과에서 따로 확인합니다.</div></div>`;bindScope();
}
function renderDiagnosisPanel(root){
  const d=pensionDiagnosis();root.innerHTML=`<div class="stack"><section class="card rc6Diagnosis ${d.tone}"><div class="rc6DiagHead"><span>현재 판단</span><b>${esc(d.state)}</b></div><h2>${esc(d.title)}</h2><p>${esc(d.reason)}</p><div class="rc6DiagAction"><small>지금 할 일 하나</small><strong>${esc(d.action)}</strong></div></section><section class="rc6Avoid"><b>지금 하지 않아도 되는 일</b><span>${esc(d.avoid)}</span></section><section class="card"><div class="sectionTitle">판단에 사용한 숫자</div><div class="r5Evidence">${d.evidence.map(([k,v])=>`<div><small>${esc(k)}</small><b>${esc(v)}</b></div>`).join('')}</div></section><button class="btn primary full" id="diagnosisAction">${esc(d.action)}</button><div class="v12Model">저장된 데이터와 설정을 이용한 규칙 기반 진단입니다. 시장 예측이나 투자 권유가 아닙니다.</div></div>`;document.getElementById('diagnosisAction').onclick=()=>runDiagnosisAction(d);
}
function bindScope(){document.getElementById('analysisScope')?.addEventListener('change',e=>{state.ui.analysisScope=e.target.value;saveState({quiet:true});renderAnalysisContent()})}
function renderAnalysis(){
  const panel=state.ui.analysisPanel;if(!['performance','cashflow','diagnosis'].includes(panel))state.ui.analysisPanel='performance';const cls=panel==='cashflow'?'i1':panel==='diagnosis'?'i2':'';
  document.getElementById('analysis').innerHTML=`<div class="segment three"><i class="segmentIndicator ${cls}"></i><button data-analysis="performance" class="${panel==='performance'?'active':''}">성과</button><button data-analysis="cashflow" class="${panel==='cashflow'?'active':''}">현금흐름</button><button data-analysis="diagnosis" class="${panel==='diagnosis'?'active':''}">진단</button></div><div id="analysisContent"></div>`;
  document.querySelectorAll('[data-analysis]').forEach(b=>b.onclick=()=>{state.ui.analysisPanel=b.dataset.analysis;saveState({quiet:true});renderAnalysis()});renderAnalysisContent();
}
function renderAnalysisContent(){const root=document.getElementById('analysisContent');if(!root)return;if(state.ui.analysisPanel==='cashflow')renderCashflowPanel(root);else if(state.ui.analysisPanel==='diagnosis')renderDiagnosisPanel(root);else renderPerformancePanel(root)}
function renderAccumulation(root){
  const out=retirementOutlook(),base=out.base,extra=retirementScenario({monthlyExtra:100000}),lower=retirementScenario({annualRate:Number(state.settings.returnRate)-1}),late=retirementScenario({retirementAge:Number(state.profile.retirementAge)+1}),rows=base.projection,milestones=[state.profile.age,40,50,60,state.profile.retirementAge].filter((v,i,a)=>v>=state.profile.age&&v<=state.profile.retirementAge&&a.indexOf(v)===i).map(age=>rows.find(r=>r.age===age)).filter(Boolean);
  root.innerHTML=`<div class="stack"><section class="card rc6FutureHero"><div class="r5FutureTop"><span>입력한 개인연금 계좌만</span><b>${Math.round(out.progress)}%</b></div><div class="rc6HeroLabel">${state.profile.retirementAge}세부터 예상 개인연금 월수령</div><div class="r5FutureMonthly"><span>약 월</span> <strong>${man(base.realMonthly)}</strong></div><div class="rc6Range">보수 ${man(out.conservative.realMonthly)} ~ 기준 ${man(base.realMonthly)}</div><div class="r5FutureGap">${out.gap>0?`목표 ${man(out.goal)}까지 월 ${man(out.gap)} 부족`:`목표 ${man(out.goal)} 달성 범위`}</div>${progressBar(out.progress)}<small>국민연금·주택·세금·수수료는 포함하지 않은 개인연금 계좌 추정입니다.</small></section><section class="card"><div class="sectionTitle">무엇을 바꾸면 달라질까</div><div class="r5Scenario"><button data-scenario="extra"><span>월 10만원 추가</span><b class="good">월 +${man(Math.max(0,extra.realMonthly-base.realMonthly))}</b></button><button data-scenario="lower"><span>수익률 1%p 낮음</span><b class="bad">월 ${man(lower.realMonthly)}</b></button><button data-scenario="late"><span>개시 1년 늦춤</span><b class="good">월 +${man(Math.max(0,late.realMonthly-base.realMonthly))}</b></button></div></section><section class="card"><div class="sectionTitle">연금 개시까지 자산 경로</div>${simpleLineChart(rows.map((r,i)=>({...r,year:r.age})), 'end')}<div class="rc6FuturePoint"><b>${state.profile.retirementAge}세 예상 ${man(base.futureAsset)}</b><span>누적 순납입 ${man(rows.at(-1)?.cumulative||0)}</span></div></section><details class="card r5Milestones"><summary>나이별 예상자산 자세히</summary><div>${milestones.map(r=>`<div class="r5Milestone"><span>${r.age}세</span><b>${man(r.end)}</b><small>순납입 ${man(r.cumulative)}</small></div>`).join('')}</div></details><button class="btn full" id="futureSettings">가정 변경하기</button></div>`;
  document.getElementById('futureSettings').onclick=()=>openSettings('future');
}
function renderWithdrawal(root){
  const out=retirementOutlook(),w=out.base;root.innerHTML=`<div class="stack"><section class="card rc6FutureHero"><div class="r5FutureTop"><span>${state.settings.withdrawYears}년 수령 가정</span><b>${state.settings.withdrawReturn}%</b></div><div class="rc6HeroLabel">오늘 돈 가치 예상 월수령</div><div class="r5FutureMonthly"><span>약 월</span> <strong>${man(w.realMonthly)}</strong></div><div class="rc6Range">연금 개시 시 첫 월 약 ${man(w.nominalFirstMonthly)}</div><small>수령 중 수익률과 물가를 반영해 설정 기간 동안 균등하게 인출하는 계산입니다.</small></section><section class="card"><div class="sectionTitle">계산 기준</div><div class="r5Evidence"><div><small>개시 예상자산</small><b>${man(w.futureAsset)}</b></div><div><small>현재가치 환산자산</small><b>${man(w.assetToday)}</b></div><div><small>수령 기간</small><b>${state.settings.withdrawYears}년</b></div><div><small>실질 수령 중 수익률</small><b>${(w.realAnnual*100).toFixed(1)}%</b></div></div></section><section class="card brief"><div class="briefTitle">주의</div><p>실제 연금수령 한도, 세금, 수수료, 수익률 순서에 따라 달라질 수 있습니다. 이 값은 수령 계획 비교용입니다.</p></section><button class="btn full" id="withdrawSettings">가정 변경하기</button></div>`;document.getElementById('withdrawSettings').onclick=()=>openSettings('future');
}
function renderFuture(){
  const panel=state.ui.futurePanel==='withdraw'?'withdraw':'accum';document.getElementById('future').innerHTML=`<div class="segment two"><i class="segmentIndicator ${panel==='withdraw'?'right':''}"></i><button data-future="accum" class="${panel==='accum'?'active':''}">적립 결과</button><button data-future="withdraw" class="${panel==='withdraw'?'active':''}">수령 계획</button></div><div id="futureContent"></div>`;document.querySelectorAll('[data-future]').forEach(b=>b.onclick=()=>{state.ui.futurePanel=b.dataset.future;saveState({quiet:true});renderFuture()});const root=document.getElementById('futureContent');panel==='withdraw'?renderWithdrawal(root):renderAccumulation(root);
}
function runDiagnosisAction(d){
  if(d.actionType==='clear-sample')document.getElementById('startMyData')?.click();else if(d.actionType==='snapshot')openForm('snapshot');else if(d.actionType==='contribution')openForm('contribution');else if(d.actionType==='settings')openSettings();else if(d.actionType==='account-irp')navigate('account','irp');else if(d.actionType==='account')navigate('account');else if(d.actionType==='future')navigate('future');else toast('현재 계획을 유지하세요');
}
function renderAll(keepScreen=false){
  state.profile.age=clamp(CURRENT_YEAR-state.profile.birthYear,0,100);document.getElementById('headerSub').textContent=`${state.profile.age}세 · ${state.profile.retirementAge}세 연금 개시`;renderHome();renderAccount();renderAnalysis();renderFuture();if(!keepScreen)window.scrollTo(0,0);applyScreen(state.ui.screen||'home',{history:false,persist:false});
}
window.PensionViews={renderHome,renderAccount,renderAnalysis,renderFuture,renderAll,renderAnalysisContent,runDiagnosisAction};
